# Sample Data Wrangling

For the module nine project you are required to produce coding samples for how you wrangled, ie cleaned, your dataset as one piece of your project submission. This Notebook is provided with some sample data wrangling from module two. You may copy examples from the code blocks herein to include in your final submission.

<div class="alert alert-block alert-info">
    <span style="color:black"><b><i>Activity Code Submission:</i></b> You will complete your assignment code in the <b>Module_Nine_Project.ipynb</b> Notebook file from the filetree on the left that is pre-templated for your modification in accordance with the assignment instructions.</span>
</div>

### Data Source Information
The sourcing information for the data sets can be found in the `README.md` file within the data folder.

To use this sample script for your selected data set, you can copy the desired code blocks to the Module_Nine_Project Notebook that you will use for your project submission, or replace the sample data path below keeping in mind you will need to copy the items to the required Project Notebook for inclusion in your project submission.

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>To Begin:</i></b> replace the <mark>data/sample_use_only/titanic_raw.csv</mark> sample data path with the path to your selected data set.</span>
</div>

In [1]:
reference_file = "data/sample_use_only/titanic_raw.csv"

## Installing Required Packages
If you have additional packages that you would like to use or install, add them to the **requirements.txt** file then run the next block.

In [2]:
!pip install --upgrade pip

Requirement already satisfied: pip in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (25.1.1)

In [3]:
!pip install -r sample_requirements.txt

Requirement already satisfied: ydata-profiling==4.16.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from -r sample_requirements.txt (line 1)) (4.16.1)
Requirement already satisfied: openpyxl==3.1.3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from -r sample_requirements.txt (line 2)) (3.1.3)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (3.7.1)
Requirement already satisfied: pydantic>=2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.11.4)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.24.2)
Requirement already satisfied: htmlmin==0.1.12 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.30.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.12.2)
Requirement already satisfied: multimethod<2,>=1.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (4.4.2)
Requirement already satisfied: imagehash==4.3.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.9.4)
Requirement already satisfied: dacite>=1.8 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.61.0)
Requirement already satisfied: et-xmlfile in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from openpyxl==3.1.3->-r sample_requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: PyWavelets in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.8.0)
Requirement already satisfied: pillow in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from phik<0.13,>=0.11.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2023.5.7)

Requirement already satisfied: patsy>=0.5.6 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: typing_extensions>=4.10.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from typeguard<5,>=3->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (4.13.2)
Requirement already satisfied: attrs>=19.3.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: networkx>=2.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (3.4.2)
Requirement already satisfied: puremagic in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.29)
Requirement already satisfied: annotated-types>=0.6.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.4.0)
Requirement already satisfied: six>=1.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.16.0)

## Import the Required Packages
If you have additional packages that you would like to import, add them here.

In [4]:
import pandas as pd
import numpy as np

## Loading the Data
After you have selected your data set that wish to wrangle, replace the reference file path in the code block at the top of this Notebook, then run the following block.

In [5]:
raw_data = pd.read_csv(reference_file)
raw_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Cleaning the Data
The sections that follow have some pre-templated steps to examine and clean data. The columns or specified attributes will need to be replaced for your respective dataset that you are cleaning. You may also need to add different cleaning options from your reading as this provides an example starting point to work with your selected dataset.

***Remember to add comments as you go.***

## Columns

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the column values are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

In [6]:
raw_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### Renaming Columns
If any of the columns in your dataset need renamed, you can use the following examples to update your column names.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the column values selected below are from the sample data and will need replaced before running the block with your dataset.</span>
</div>

In the example below we want to rename the `PassengerId` column `ID` and the `Pclass` column to say `Class` as we are considering merging this data with another dataset later which will use these columns as shared keys. For this task, we use the `rename()` method and pass in a dictionary mapping the column names to their new names. We can pass `inplace=True` to change our original dataframe instead of getting a new one back, or `inplace=False` to create a new dataframe to compare against our original. In the example, we are creating a new dataframe that we will use for all follow-on cleaning actions.

In [7]:
clean_data = raw_data.rename(
    columns={
        'PassengerId': 'ID',
        'Pclass': 'Class'
    }, inplace=False
)
clean_data.head()

,ID,Survived,Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Working with Missing Values
Lets take a look at the output of `info()` method to get a quick view of additional information about the data set which can help pinpoint missing values and wrong data types.


<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset.</span>
</div>

In the example dataset, we have an index range of 891 entries or rows available in the sample dataset. Using that foundational data, we can examine the null counts to identify which columns may have null, missing or NaN values. In the example dataset, the following columns indicate potential issues in the data: Age, Cabin, and Embarked.

In [8]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        891 non-null    int64
 1   Survived  891 non-null    int64
 2   Class     891 non-null    int64
 3   Name      891 non-null    object
 4   Sex       891 non-null    object
 5   Age       714 non-null    float64
 6   SibSp     891 non-null    int64
 7   Parch     891 non-null    int64
 8   Ticket    891 non-null    object
 9   Fare      891 non-null    float64
 10  Cabin     204 non-null    object
 11  Embarked  889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### isnull()
We can also use the `isnull()` method to return a dataframe of boolean values where **True** represents missing data.

In [9]:
clean_data.isnull()

,ID,Survived,Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

For the example dataset, since we already saw from the `info()` method that only three columns were impacted by data issues, the output of the `isnull()` method may not be as helpful so we can limit the output for a given column to check for nulls or use the output for other cleaning functions as shown in the example below.

For your selected dataset, you can replace the Column name `Age` with your selected column that you would like to assess expanding on the dataset for additional afflicted columns for cleaning.

In [10]:
bool_series = pd.isnull(clean_data["Age"])
missing_age_data = clean_data[bool_series]
missing_age_data

,ID,Survived,Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Using Numpy to Find Missing Data using a Dictionary Comprehension
Rather than do this for each column, we can write a function that will use a [dictionary comprehension](https://www.python.org/dev/peps/pep-0274/) to check all the columns for us:

In [11]:
def get_nan_count(clean_data):
    return {
        col: clean_data[clean_data[col].isin([np.nan])].shape[0] for col in clean_data.columns
    }

get_nan_count(clean_data)

{'ID': 0,
 'Survived': 0,
 'Class': 0,
 'Name': 0,
 'Sex': 0,
 'Age': 177,
 'SibSp': 0,
 'Parch': 0,
 'Ticket': 0,
 'Fare': 0,
 'Cabin': 687,
 'Embarked': 2}

###  Filling Missing Values Using fillna(), replace() and interpolate()
From the example output, there were 177 rows of data that were impacted by missing data from the sample dataset. For your selected dataset you should evaluate your columns you identified with missing or null values and expand to the afflicted columns to clean your respective dataset.

#### Filling Missing Values with a Specific Value Using fillna()
Here in the example, we will fill in the missing `Age` values with an age of `0` based on dataset knowledge, you will make your own decisions for how you handle your missing data and justify your decisions as part of your activity reflection.

In [12]:
clean_data["Age"].fillna('0', inplace = True )
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        891 non-null    int64
 1   Survived  891 non-null    int64
 2   Class     891 non-null    int64
 3   Name      891 non-null    object
 4   Sex       891 non-null    object
 5   Age       891 non-null    object
 6   SibSp     891 non-null    int64
 7   Parch     891 non-null    int64
 8   Ticket    891 non-null    object
 9   Fare      891 non-null    float64
 10  Cabin     204 non-null    object
 11  Embarked  889 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 83.7+ KB

If you do not find the info() method helpful to find the missing data, you can use the previously created get_nan_count() we created to view the missing data by column. In the sample dataset you will see there are still two columns with null values to be addressed.

In [13]:
get_nan_count(clean_data)

{'ID': 0,
 'Survived': 0,
 'Class': 0,
 'Name': 0,
 'Sex': 0,
 'Age': 0,
 'SibSp': 0,
 'Parch': 0,
 'Ticket': 0,
 'Fare': 0,
 'Cabin': 687,
 'Embarked': 2}

<div class="alert alert-block alert-warning">
    <span style="color:black"><b><i>Example Data:</i></b> Your selected dataset is likely to have several columns where the data is missing, create additional code blocks as necessary to clean your data according to the assignment requirements. Here we will clean the columns with different methods to show you different use cases, you will modify the code herein to the methods you feel are appropriate for your selected data set.
</div>

#### Replacing Missing Values Using replace()
Here in the example, we will replace the missing `Embarked` values with an age of `U` to represent **Unknown** based on dataset knowledge, you will make your own decisions for how you handle your missing data and justify your decisions as part of your activity reflection.

In [14]:
clean_data["Embarked"].replace(to_replace=np.nan, value='U', inplace = True )
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        891 non-null    int64
 1   Survived  891 non-null    int64
 2   Class     891 non-null    int64
 3   Name      891 non-null    object
 4   Sex       891 non-null    object
 5   Age       891 non-null    object
 6   SibSp     891 non-null    int64
 7   Parch     891 non-null    int64
 8   Ticket    891 non-null    object
 9   Fare      891 non-null    float64
 10  Cabin     204 non-null    object
 11  Embarked  891 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 83.7+ KB

#### Dropping Missing Values in Pandas Using dropna()
Here in the example, we will drop the column `Cabin` based on dataset knowledge, you will make your own decisions for how you handle your missing data and justify your decisions as part of your activity reflection. Keep in mind that if you use dropna() with an axis of 1, where there are nulls or missing values in more than one column, it may drop all columns that have null or missing values.

In [15]:
clean_data.dropna(axis=1, inplace = True )
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        891 non-null    int64
 1   Survived  891 non-null    int64
 2   Class     891 non-null    int64
 3   Name      891 non-null    object
 4   Sex       891 non-null    object
 5   Age       891 non-null    object
 6   SibSp     891 non-null    int64
 7   Parch     891 non-null    int64
 8   Ticket    891 non-null    object
 9   Fare      891 non-null    float64
 10  Embarked  891 non-null    object
dtypes: float64(1), int64(5), object(5)
memory usage: 76.7+ KB

### Duplicated Records
Some datasets may include duplicated records. 

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the data types are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

The sample dataset does not have any duplicated records, though some code examples will be provided here for your use against your selected dataset, update the actions you would like to take against your selected dataset to clean it to your preference.

In [16]:
clean_data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

## Data Types
<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the data types are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

You can use either the .dtypes property to view the data types for each column in the data frame, or the .info() method which will provide additional insights into the columns.

In [17]:
clean_data.dtypes

ID            int64
Survived      int64
Class         int64
Name         object
Sex          object
Age          object
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Embarked     object
dtype: object

### Data Type Conversion
If any of the data types in your dataset need to be modified or redefined, you can use the following block to update your column data types.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the columns and data types selected below are from the sample data and will need replaced before running the block with your dataset.</span>
</div>

In the example below we want to modify the data values and type for the `Survived` column to represent a `bool`.

If you do not have any type conversions required for your data set, feel free to comment out the existing example and add a comment as applicable in the code block below:

In [18]:
clean_data = clean_data.assign(
    Survived=lambda x: x.Survived.astype('bool')
)
clean_data.dtypes

ID            int64
Survived       bool
Class         int64
Name         object
Sex          object
Age          object
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Embarked     object
dtype: object

We will take a quick look at the output of the describe method.

In [19]:
clean_data.describe()

               ID       Class       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000
mean   446.000000    2.308642    0.523008    0.381594   32.204208
std    257.353842    0.836071    1.102743    0.806057   49.693429
min      1.000000    1.000000    0.000000    0.000000    0.000000
25%    223.500000    2.000000    0.000000    0.000000    7.910400
50%    446.000000    3.000000    0.000000    0.000000   14.454200
75%    668.500000    3.000000    1.000000    0.000000   31.000000
max    891.000000    3.000000    8.000000    6.000000  512.329200

We will now take a look at the top five records in our dataframe before continue the cleaning examples.

In [20]:
clean_data.head()

,ID,Survived,Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

### Categoricals
When choosing which columns to set as categories, you will want to evaluate how many different values are available for the column.
<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output are from the sample data and will not represent your dataset until these blocks are run.</span>
</div>

Here in the example dataset, there are three values for the `Class` column, there are two values for the `Sex` column, and three values for the `Embarked` column, so we will convert those to categories for furture analysis. All other columns aside from `Survived` column that we converted to a bool, have a variety of values which cannot be easily placed into categories without first creating bins to use as categoricals which will we learn more about in the coming modules.

In [21]:
clean_data_with_categories = clean_data.assign(
    Class=clean_data.Class.astype('category'),
    Sex=clean_data.Sex.astype('category'),
    Embarked=clean_data.Embarked.astype('category')
)
clean_data_with_categories.dtypes

ID             int64
Survived        bool
Class       category
Name          object
Sex         category
Age           object
SibSp          int64
Parch          int64
Ticket        object
Fare         float64
Embarked    category
dtype: object

In [22]:
clean_data_with_categories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        891 non-null    int64
 1   Survived  891 non-null    bool
 2   Class     891 non-null    category
 3   Name      891 non-null    object
 4   Sex       891 non-null    category
 5   Age       891 non-null    object
 6   SibSp     891 non-null    int64
 7   Parch     891 non-null    int64
 8   Ticket    891 non-null    object
 9   Fare      891 non-null    float64
 10  Embarked  891 non-null    category
dtypes: bool(1), category(3), float64(1), int64(3), object(3)
memory usage: 52.8+ KB

In [23]:
clean_data_with_categories.describe()

               ID       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000
mean   446.000000    0.523008    0.381594   32.204208
std    257.353842    1.102743    0.806057   49.693429
min      1.000000    0.000000    0.000000    0.000000
25%    223.500000    0.000000    0.000000    7.910400
50%    446.000000    0.000000    0.000000   14.454200
75%    668.500000    1.000000    0.000000   31.000000
max    891.000000    8.000000    6.000000  512.329200

In [24]:
clean_data_with_categories.describe(include='category')

        Class   Sex Embarked
count     891   891      891
unique      3     2        4
top         3  male        S
freq      491   577      644

## Tabular Format
<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output are from the sample data and will not represent your dataset until these blocks are run. Validate your table represents your dataset before activity submission.</span>
</div>

In [25]:
len(clean_data_with_categories)

891

In [26]:
pd.set_option('display.max_rows', None)
clean_data_with_categories

,ID,Survived,Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
5,6,False,3,"Moran, Mr. James",male,0,0,0,330877,8.4583,Q
6,7,False,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
7,8,False,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S
8,9,True,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S
9,10,True,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C
10,11,True,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,S
11,12,True,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S
12,13,False,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,S
13,14,False,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,S
14,15,False,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,S
15,16,True,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,S
16,17,False,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,Q
17,18,True,2,"Williams, Mr. Charles Eugene",male,0,0,0,244373,13.0000,S
18,19,False,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,S
19,20,True,3,"Masselmani, Mrs. Fatima",female,0,0,0,2649,7.2250,C
20,21,False,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,S
21,22,True,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,S
22,23,True,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,Q
23,24,True,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,S
24,25,False,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,S
25,26,True,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,S
26,27,False,3,"Emir, Mr. Farred Chehab",male,0,0,0,2631,7.2250,C
27,28,False,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,S
28,29,True,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,0,0,0,330959,7.8792,Q
29,30,False,3,"Todoroff, Mr. Lalio",male,0,0,0,349216,7.8958,S
30,31,False,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,C
31,32,True,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,0,1,0,PC 17569,146.5208,C
32,33,True,3,"Glynn, Miss. Mary Agatha",female,0,0,0,335677,7.7500,Q
33,34,False,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,S
34,35,False,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,C
35,36,False,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,S
36,37,True,3,"Mamee, Mr. Hanna",male,0,0,0,2677,7.2292,C
37,38,False,3,"Cann, Mr. Ernest Charles",male,21.0,0,0,A./5. 2152,8.0500,S
38,39,False,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,S
39,40,True,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,C
40,41,False,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,S
41,42,False,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,S
42,43,False,3,"Kraeff, Mr. Theodor",male,0,0,0,349253,7.8958,C
43,44,True,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,C
44,45,True,3,"Devaney, Miss. Margaret Delia",female,19.0,0,0,330958,7.8792,Q
45,46,False,3,"Rogers, Mr. William John",male,0,0,0,S.C./A.4. 23567,8.0500,S
46,47,False,3,"Lennon, Mr. Denis",male,0,1,0,370371,15.5000,Q
47,48,True,3,"O'Driscoll, Miss. Bridget",female,0,0,0,14311,7.7500,Q
48,49,False,3,"Samaan, Mr. Youssef",male,0,2,0,2662,21.6792,C
49,50,False,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,S
50,51,False,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,S
51,52,False,3,"Nosworthy, Mr. Richard Cater",male,21.0,0,0,A/4. 39886,7.8000,S
52,53,True,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,C
53,54,True,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",female,29.0,1,0,2926,26.0000,S
54,55,False,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,C
55,56,True,1,"Woolner, Mr. Hugh",male,0,0,0,19947,35.5000,S
56,57,True,2,"Rugg, Miss. Emily",female,21.0,0,0,C.A. 31026,10.5000,S
57,58,False,3,"Novel, Mr. Mansouer",male,28.5,0,0,2697,7.2292,C
58,59,True,2,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.7500,S
59,60,False,3,"Goodwin, Master. William Frederick",male,11.0,5,2,CA 2144,46.9000,S
60,61,False,3,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,C
61,62,True,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,U
62,63,False,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.4750,S
63,64,False,3,"Skoog, Master. Harald",male,4.0,3,2,347088,27.9000,S
64,65,False,1,"Stewart, Mr. Albert A",male,0,0,0,PC 17605,27.7208,C
65,66,True,3,"Moubarek, Master. Gerios",male,0,1,1,2661,15.2458,C
66,67,True,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.0,0,0,C.A. 29395,10.5000,S
67,68,False,3,"Crease, Mr. Ernest James",male,19.0,0,0,S.P. 3464,8.1583,S
68,69,True,3,"Andersson, Miss. Erna Alexandra",female,17.0,4,2,3101281,7.9250,S
69,70,False,3,"Kink, Mr. Vincenz",male,26.0,2,0,315151,8.6625,S
70,71,False,2,"Jenkin, Mr. Stephen Curnow",male,32.0,0,0,C.A. 33111,10.5000,S
71,72,False,3,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.9000,S
72,73,False,2,"Hood, Mr. Ambrose Jr",male,21.0,0,0,S.O.C. 14879,73.5000,S
73,74,False,3,"Chronopoulos, Mr. Apostolos",male,26.0,1,0,2680,14.4542,C
74,75,True,3,"Bing, Mr. Lee",male,32.0,0,0,1601,56.4958,S
75,76,False,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,S
76,77,False,3,"Staneff, Mr. Ivan",male,0,0,0,349208,7.8958,S
77,78,False,3,"Moutal, Mr. Rahamin Haim",male,0,0,0,374746,8.0500,S
78,79,True,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,S
79,80,True,3,"Dowdell, Miss. Elizabeth",female,30.0,0,0,364516,12.4750,S
80,81,False,3,"Waelens, Mr. Achille",male,22.0,0,0,345767,9.0000,S
81,82,True,3,"Sheerlinck, Mr. Jan Baptist",male,29.0,0,0,345779,9.5000,S
82,83,True,3,"McDermott, Miss. Brigdet Delia",female,0,0,0,330932,7.7875,Q
83,84,False,1,"Carrau, Mr. Francisco M",male,28.0,0,0,113059,47.1000,S
84,85,True,2,"Ilett, Miss. Bertha",female,17.0,0,0,SO/C 14885,10.5000,S
85,86,True,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.0,3,0,3101278,15.8500,S
86,87,False,3,"Ford, Mr. William Neal",male,16.0,1,3,W./C. 6608,34.3750,S
87,88,False,3,"Slocovski, Mr. Selman Francis",male,0,0,0,SOTON/OQ 392086,8.0500,S
88,89,True,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,S
89,90,False,3,"Celotti, Mr. Francesco",male,24.0,0,0,343275,8.0500,S
90,91,False,3,"Christmann, Mr. Emil",male,29.0,0,0,343276,8.0500,S
91,92,False,3,"Andreasson, Mr. Paul Edvin",male,20.0,0,0,347466,7.8542,S
92,93,False,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,S
93,94,False,3,"Dean, Mr. Bertram Frank",male,26.0,1,2,C.A. 2315,20.5750,S
94,95,False,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,S
95,96,False,3,"Shorney, Mr. Charles Joseph",male,0,0,0,374910,8.0500,S
96,97,False,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,C
97,98,True,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,C
98,99,True,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,S
99,100,False,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,S
100,101,False,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,S
101,102,False,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,0,0,0,349215,7.8958,S
102,103,False,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,S
103,104,False,3,"Johansson, Mr. Gustaf Joel",male,33.0,0,0,7540,8.6542,S
104,105,False,3,"Gustafsson, Mr. Anders Vilhelm",male,37.0,2,0,3101276,7.9250,S
105,106,False,3,"Mionoff, Mr. Stoytcho",male,28.0,0,0,349207,7.8958,S
106,107,True,3,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.6500,S
107,108,True,3,"Moss, Mr. Albert Johan",male,0,0,0,312991,7.7750,S
108,109,False,3,"Rekic, Mr. Tido",male,38.0,0,0,349249,7.8958,S
109,110,True,3,"Moran, Miss. Bertha",female,0,1,0,371110,24.1500,Q
110,111,False,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,S
111,112,False,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,C
112,113,False,3,"Barton, Mr. David John",male,22.0,0,0,324669,8.0500,S
113,114,False,3,"Jussila, Miss. Katriina",female,20.0,1,0,4136,9.8250,S
114,115,False,3,"Attalah, Miss. Malake",female,17.0,0,0,2627,14.4583,C
115,116,False,3,"Pekoniemi, Mr. Edvard",male,21.0,0,0,STON/O 2. 3101294,7.9250,S
116,117,False,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,Q
117,118,False,2,"Turpin, Mr. William John Robert",male,29.0,1,0,11668,21.0000,S
118,119,False,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,C
119,120,False,3,"Andersson, Miss. Ellis Anna Maria",female,2.0,4,2,347082,31.2750,S
120,121,False,2,"Hickman, Mr. Stanley George",male,21.0,2,0,S.O.C. 14879,73.5000,S
121,122,False,3,"Moore, Mr. Leonard Charles",male,0,0,0,A4. 54510,8.0500,S
122,123,False,2,"Nasser, Mr. Nicholas",male,32.5,1,0,237736,30.0708,C
123,124,True,2,"Webber, Miss. Susan",female,32.5,0,0,27267,13.0000,S
124,125,False,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,S
125,126,True,3,"Nicola-Yarred, Master. Elias",male,12.0,1,0,2651,11.2417,C
126,127,False,3,"McMahon, Mr. Martin",male,0,0,0,370372,7.7500,Q
127,128,True,3,"Madsen, Mr. Fridtjof Arne",male,24.0,0,0,C 17369,7.1417,S
128,129,True,3,"Peter, Miss. Anna",female,0,1,1,2668,22.3583,C
129,130,False,3,"Ekstrom, Mr. Johan",male,45.0,0,0,347061,6.9750,S
130,131,False,3,"Drazenoic, Mr. Jozef",male,33.0,0,0,349241,7.8958,C
131,132,False,3,"Coelho, Mr. Domingos Fernandeo",male,20.0,0,0,SOTON/O.Q. 3101307,7.0500,S
132,133,False,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,14.5000,S
133,134,True,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.0,1,0,228414,26.0000,S
134,135,False,2,"Sobey, Mr. Samuel James Hayden",male,25.0,0,0,C.A. 29178,13.0000,S
135,136,False,2,"Richard, Mr. Emile",male,23.0,0,0,SC/PARIS 2133,15.0458,C
136,137,True,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,S
137,138,False,1,"Futrelle, Mr. Jacques Heath",male,37.0,1,0,113803,53.1000,S
138,139,False,3,"Osen, Mr. Olaf Elon",male,16.0,0,0,7534,9.2167,S
139,140,False,1,"Giglio, Mr. Victor",male,24.0,0,0,PC 17593,79.2000,C
140,141,False,3,"Boulos, Mrs. Joseph (Sultana)",female,0,0,2,2678,15.2458,C
141,142,True,3,"Nysten, Miss. Anna Sofia",female,22.0,0,0,347081,7.7500,S
142,143,True,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...",female,24.0,1,0,STON/O2. 3101279,15.8500,S
143,144,False,3,"Burke, Mr. Jeremiah",male,19.0,0,0,365222,6.7500,Q
144,145,False,2,"Andrew, Mr. Edgardo Samuel",male,18.0,0,0,231945,11.5000,S
145,146,False,2,"Nicholls, Mr. Joseph Charles",male,19.0,1,1,C.A. 33112,36.7500,S
146,147,True,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.0,0,0,350043,7.7958,S
147,148,False,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.0,2,2,W./C. 6608,34.3750,S
148,149,False,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.5,0,2,230080,26.0000,S
149,150,False,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,S
150,151,False,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,S
151,152,True,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,S
152,153,False,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,S
153,154,False,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,S
154,155,False,3,"Olsen, Mr. Ole Martin",male,0,0,0,Fa 265302,7.3125,S
155,156,False,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,C
156,157,True,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.0,0,0,35851,7.7333,Q
157,158,False,3,"Corn, Mr. Harry",male,30.0,0,0,SOTON/OQ 392090,8.0500,S
158,159,False,3,"Smiljanic, Mr. Mile",male,0,0,0,315037,8.6625,S
159,160,False,3,"Sage, Master. Thomas Henry",male,0,8,2,CA. 2343,69.5500,S
160,161,False,3,"Cribb, Mr. John Hatfield",male,44.0,0,1,371362,16.1000,S
161,162,True,2,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Mi...",female,40.0,0,0,C.A. 33595,15.7500,S
162,163,False,3,"Bengtsson, Mr. John Viktor",male,26.0,0,0,347068,7.7750,S
163,164,False,3,"Calic, Mr. Jovo",male,17.0,0,0,315093,8.6625,S
164,165,False,3,"Panula, Master. Eino Viljami",male,1.0,4,1,3101295,39.6875,S
165,166,True,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.0,0,2,363291,20.5250,S
166,167,True,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,0,0,1,113505,55.0000,S
167,168,False,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,347088,27.9000,S
168,169,False,1,"Baumann, Mr. John D",male,0,0,0,PC 17318,25.9250,S
169,170,False,3,"Ling, Mr. Lee",male,28.0,0,0,1601,56.4958,S
170,171,False,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,S
171,172,False,3,"Rice, Master. Arthur",male,4.0,4,1,382652,29.1250,Q
172,173,True,3,"Johnson, Miss. Eleanor Ileen",female,1.0,1,1,347742,11.1333,S
173,174,False,3,"Sivola, Mr. Antti Wilhelm",male,21.0,0,0,STON/O 2. 3101280,7.9250,S
174,175,False,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,C
175,176,False,3,"Klasen, Mr. Klas Albin",male,18.0,1,1,350404,7.8542,S
176,177,False,3,"Lefebre, Master. Henry Forbes",male,0,3,1,4133,25.4667,S
177,178,False,1,"Isham, Miss. Ann Elizabeth",female,50.0,0,0,PC 17595,28.7125,C
178,179,False,2,"Hale, Mr. Reginald",male,30.0,0,0,250653,13.0000,S
179,180,False,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0000,S
180,181,False,3,"Sage, Miss. Constance Gladys",female,0,8,2,CA. 2343,69.5500,S
181,182,False,2,"Pernot, Mr. Rene",male,0,0,0,SC/PARIS 2131,15.0500,C
182,183,False,3,"Asplund, Master. Clarence Gustaf Hugo",male,9.0,4,2,347077,31.3875,S
183,184,True,2,"Becker, Master. Richard F",male,1.0,2,1,230136,39.0000,S
184,185,True,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.0,0,2,315153,22.0250,S
185,186,False,1,"Rood, Mr. Hugh Roscoe",male,0,0,0,113767,50.0000,S
186,187,True,3,"O'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,0,1,0,370365,15.5000,Q
187,188,True,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45.0,0,0,111428,26.5500,S
188,189,False,3,"Bourke, Mr. John",male,40.0,1,1,364849,15.5000,Q
189,190,False,3,"Turcin, Mr. Stjepan",male,36.0,0,0,349247,7.8958,S
190,191,True,2,"Pinsky, Mrs. (Rosa)",female,32.0,0,0,234604,13.0000,S
191,192,False,2,"Carbines, Mr. William",male,19.0,0,0,28424,13.0000,S
192,193,True,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.0,1,0,350046,7.8542,S
193,194,True,2,"Navratil, Master. Michel M",male,3.0,1,1,230080,26.0000,S
194,195,True,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,0,0,PC 17610,27.7208,C
195,196,True,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,C
196,197,False,3,"Mernagh, Mr. Robert",male,0,0,0,368703,7.7500,Q
197,198,False,3,"Olsen, Mr. Karl Siegwart Andreas",male,42.0,0,1,4579,8.4042,S
198,199,True,3,"Madigan, Miss. Margaret ""Maggie""",female,0,0,0,370370,7.7500,Q
199,200,False,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24.0,0,0,248747,13.0000,S
200,201,False,3,"Vande Walle, Mr. Nestor Cyriel",male,28.0,0,0,345770,9.5000,S
201,202,False,3,"Sage, Mr. Frederick",male,0,8,2,CA. 2343,69.5500,S
202,203,False,3,"Johanson, Mr. Jakob Alfred",male,34.0,0,0,3101264,6.4958,S
203,204,False,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.2250,C
204,205,True,3,"Cohen, Mr. Gurshon ""Gus""",male,18.0,0,0,A/5 3540,8.0500,S
205,206,False,3,"Strom, Miss. Telma Matilda",female,2.0,0,1,347054,10.4625,S
206,207,False,3,"Backstrom, Mr. Karl Alfred",male,32.0,1,0,3101278,15.8500,S
207,208,True,3,"Albimona, Mr. Nassef Cassem",male,26.0,0,0,2699,18.7875,C
208,209,True,3,"Carr, Miss. Helen ""Ellen""",female,16.0,0,0,367231,7.7500,Q
209,210,True,1,"Blank, Mr. Henry",male,40.0,0,0,112277,31.0000,C
210,211,False,3,"Ali, Mr. Ahmed",male,24.0,0,0,SOTON/O.Q. 3101311,7.0500,S
211,212,True,2,"Cameron, Miss. Clear Annie",female,35.0,0,0,F.C.C. 13528,21.0000,S
212,213,False,3,"Perkin, Mr. John Henry",male,22.0,0,0,A/5 21174,7.2500,S
213,214,False,2,"Givard, Mr. Hans Kristensen",male,30.0,0,0,250646,13.0000,S
214,215,False,3,"Kiernan, Mr. Philip",male,0,1,0,367229,7.7500,Q
215,216,True,1,"Newell, Miss. Madeleine",female,31.0,1,0,35273,113.2750,C
216,217,True,3,"Honkanen, Miss. Eliina",female,27.0,0,0,STON/O2. 3101283,7.9250,S
217,218,False,2,"Jacobsohn, Mr. Sidney Samuel",male,42.0,1,0,243847,27.0000,S
218,219,True,1,"Bazzani, Miss. Albina",female,32.0,0,0,11813,76.2917,C
219,220,False,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.5000,S
220,221,True,3,"Sunderland, Mr. Victor Francis",male,16.0,0,0,SOTON/OQ 392089,8.0500,S
221,222,False,2,"Bracken, Mr. James H",male,27.0,0,0,220367,13.0000,S
222,223,False,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.0500,S
223,224,False,3,"Nenkoff, Mr. Christo",male,0,0,0,349234,7.8958,S
224,225,True,1,"Hoyt, Mr. Frederick Maxfield",male,38.0,1,0,19943,90.0000,S
225,226,False,3,"Berglund, Mr. Karl Ivar Sven",male,22.0,0,0,PP 4348,9.3500,S
226,227,True,2,"Mellors, Mr. William John",male,19.0,0,0,SW/PP 751,10.5000,S
227,228,False,3,"Lovell, Mr. John Hall (""Henry"")",male,20.5,0,0,A/5 21173,7.2500,S
228,229,False,2,"Fahlstrom, Mr. Arne Jonas",male,18.0,0,0,236171,13.0000,S
229,230,False,3,"Lefebre, Miss. Mathilde",female,0,3,1,4133,25.4667,S
230,231,True,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",female,35.0,1,0,36973,83.4750,S
231,232,False,3,"Larsson, Mr. Bengt Edvin",male,29.0,0,0,347067,7.7750,S
232,233,False,2,"Sjostedt, Mr. Ernst Adolf",male,59.0,0,0,237442,13.5000,S
233,234,True,3,"Asplund, Miss. Lillian Gertrud",female,5.0,4,2,347077,31.3875,S
234,235,False,2,"Leyson, Mr. Robert William Norman",male,24.0,0,0,C.A. 29566,10.5000,S
235,236,False,3,"Harknett, Miss. Alice Phoebe",female,0,0,0,W./C. 6609,7.5500,S
236,237,False,2,"Hold, Mr. Stephen",male,44.0,1,0,26707,26.0000,S
237,238,True,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.0,0,2,C.A. 31921,26.2500,S
238,239,False,2,"Pengelly, Mr. Frederick William",male,19.0,0,0,28665,10.5000,S
239,240,False,2,"Hunt, Mr. George Henry",male,33.0,0,0,SCO/W 1585,12.2750,S
240,241,False,3,"Zabour, Miss. Thamine",female,0,1,0,2665,14.4542,C
241,242,True,3,"Murphy, Miss. Katherine ""Kate""",female,0,1,0,367230,15.5000,Q
242,243,False,2,"Coleridge, Mr. Reginald Charles",male,29.0,0,0,W./C. 14263,10.5000,S
243,244,False,3,"Maenpaa, Mr. Matti Alexanteri",male,22.0,0,0,STON/O 2. 3101275,7.1250,S
244,245,False,3,"Attalah, Mr. Sleiman",male,30.0,0,0,2694,7.2250,C
245,246,False,1,"Minahan, Dr. William Edward",male,44.0,2,0,19928,90.0000,Q
246,247,False,3,"Lindahl, Miss. Agda Thorilda Viktoria",female,25.0,0,0,347071,7.7750,S
247,248,True,2,"Hamalainen, Mrs. William (Anna)",female,24.0,0,2,250649,14.5000,S
248,249,True,1,"Beckwith, Mr. Richard Leonard",male,37.0,1,1,11751,52.5542,S
249,250,False,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.0000,S
250,251,False,3,"Reed, Mr. James George",male,0,0,0,362316,7.2500,S
251,252,False,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29.0,1,1,347054,10.4625,S
252,253,False,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,S
253,254,False,3,"Lobb, Mr. William Arthur",male,30.0,1,0,A/5. 3336,16.1000,S
254,255,False,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41.0,0,2,370129,20.2125,S
255,256,True,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29.0,0,2,2650,15.2458,C
256,257,True,1,"Thorne, Mrs. Gertrude Maybelle",female,0,0,0,PC 17585,79.2000,C
257,258,True,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.5000,S
258,259,True,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,C
259,260,True,2,"Parrish, Mrs. (Lutie Davis)",female,50.0,0,1,230433,26.0000,S