# Sample Data Blending Preprocessing

For the module nine project you are required to produce coding samples for how you preprocessed your dataset as one piece of your project submission. This Notebook is provided with some sample data preprocessing from module three. You may copy examples from the code blocks herein to include in your final submission.

<div class="alert alert-block alert-info">
    <span style="color:black"><b><i>Activity Code Submission:</i></b> You will complete your assignment code in the <b>Module_Nine_Project.ipynb</b> Notebook file from the filetree on the left that is pre-templated for your modification in accordance with the assignment instructions.</span>
</div>


### Data Source Information
The sourcing information for the data sets can be found in the `README.md` file within the data folder.

To use this sample script for your selected data set, you can copy the desired code blocks to the Module_Nine_Project Notebook that you will use for your project submission, or replace the sample data path below keeping in mind you will need to copy the items to the required Project Notebook for inclusion in your project submission.

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>To Begin:</i></b> replace each <b>data_file_#</b> entry sample data path with the path to your selected data sets.</span>
</div>

If you choose to only use two data files instead of three, comment out the reference to data_file_3.

In [1]:
data_file_1 = "data/sample_use_only/PopulationEstimates.csv"
data_file_2 = "data/sample_use_only/Education2023.csv"
data_file_3 = "data/sample_use_only/Unemployment2023.csv"

## Installing Required Packages
If you have additional packages that you would like to use or install, add them to the **requirements.txt** file then run the next block.

In [2]:
!pip install --upgrade pip

Requirement already satisfied: pip in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (25.1.1)

In [3]:
!pip install -r sample_requirements.txt

Requirement already satisfied: ydata-profiling==4.16.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from -r sample_requirements.txt (line 1)) (4.16.1)
Requirement already satisfied: openpyxl==3.1.3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from -r sample_requirements.txt (line 2)) (3.1.3)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (3.7.1)
Requirement already satisfied: pydantic>=2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.11.4)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.24.2)
Requirement already satisfied: htmlmin==0.1.12 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.30.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.12.2)
Requirement already satisfied: multimethod<2,>=1.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.14.4)
Requirement already satisfied: typeguard<5,>=3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (4.4.2)
Requirement already satisfied: imagehash==4.3.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.9.4)
Requirement already satisfied: dacite>=1.8 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.61.0)
Requirement already satisfied: et-xmlfile in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from openpyxl==3.1.3->-r sample_requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: PyWavelets in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.8.0)
Requirement already satisfied: pillow in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from phik<0.13,>=0.11.1->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2023.5.7)

Requirement already satisfied: patsy>=0.5.6 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: typing_extensions>=4.10.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from typeguard<5,>=3->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (4.13.2)
Requirement already satisfied: attrs>=19.3.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: networkx>=2.4 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (3.4.2)
Requirement already satisfied: puremagic in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.29)
Requirement already satisfied: annotated-types>=0.6.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pydantic>=2->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (0.4.0)
Requirement already satisfied: six>=1.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r sample_requirements.txt (line 1)) (1.16.0)

## Import the Required Packages
If you have additional packages that you would like to import, add them here.

In [4]:
import pandas as pd
import numpy as np

## Loading and Preprocessing the Data
After you have selected your data set that wish to wrangle, replace the reference file path in the code block at the top of this Notebook, then run the following blocks.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you need to preprocess or clean your dataset before merging.</span>
</div>

### Data File 1 dataframe
Here we will load the data_file_1 example data, then pivot and clean it in preparation for merging with the other two selected sample files.

For your submission you will adjust the code to reflect your selected dataset.

In [5]:
data1 = pd.read_csv(data_file_1)
data1.head()

   FIPStxt State      Area_Name            Attribute        Value
0        0    US  United States      CENSUS_2020_POP  331449281.0
1        0    US  United States  ESTIMATES_BASE_2020  331464948.0
2        0    US  United States    POP_ESTIMATE_2020  331526933.0
3        0    US  United States    POP_ESTIMATE_2021  332048977.0
4        0    US  United States    POP_ESTIMATE_2022  333271411.0

In [6]:
data1_wide = data1.pivot(index=['FIPStxt','State','Area_Name'], columns='Attribute', values='Value')
data1_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54 entries, (0, 'US', 'United States') to (72000, 'PR', 'Puerto Rico')
Data columns (total 65 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   BIRTHS_2020                      53 non-null     float64
 1   BIRTHS_2021                      53 non-null     float64
 2   BIRTHS_2022                      53 non-null     float64
 3   BIRTHS_2023                      53 non-null     float64
 4   CENSUS_2020_POP                  54 non-null     float64
 5   DEATHS_2020                      53 non-null     float64
 6   DEATHS_2021                      53 non-null     float64
 7   DEATHS_2022                      53 non-null     float64
 8   DEATHS_2023                      53 non-null     float64
 9   DOMESTIC_MIG_2020                53 non-null     float64
 10  DOMESTIC_MIG_2021                53 non-null     float64
 11  DOMESTIC_MIG_2022                53 non-null     float64
 12  DOMESTIC_MIG_2023                53 non-null     float64
 13  ESTIMATES_BASE_2020              54 non-null     float64
 14  Economic_typology_2015           1 non-null      float64
 15  GQ_ESTIMATES_2020                52 non-null     float64
 16  GQ_ESTIMATES_2021                52 non-null     float64
 17  GQ_ESTIMATES_2022                52 non-null     float64
 18  GQ_ESTIMATES_2023                52 non-null     float64
 19  GQ_ESTIMATES_BASE_2020           52 non-null     float64
 20  INTERNATIONAL_MIG_2020           53 non-null     float64
 21  INTERNATIONAL_MIG_2021           53 non-null     float64
 22  INTERNATIONAL_MIG_2022           53 non-null     float64
 23  INTERNATIONAL_MIG_2023           53 non-null     float64
 24  NATURAL_CHG_2020                 53 non-null     float64
 25  NATURAL_CHG_2021                 53 non-null     float64
 26  NATURAL_CHG_2022                 53 non-null     float64
 27  NATURAL_CHG_2023                 53 non-null     float64
 28  NET_MIG_2020                     53 non-null     float64
 29  NET_MIG_2021                     53 non-null     float64
 30  NET_MIG_2022                     53 non-null     float64
 31  NET_MIG_2023                     53 non-null     float64
 32  N_POP_CHG_2020                   53 non-null     float64
 33  N_POP_CHG_2021                   53 non-null     float64
 34  N_POP_CHG_2022                   53 non-null     float64
 35  N_POP_CHG_2023                   53 non-null     float64
 36  POP_ESTIMATE_2020                54 non-null     float64
 37  POP_ESTIMATE_2021                54 non-null     float64
 38  POP_ESTIMATE_2022                54 non-null     float64
 39  POP_ESTIMATE_2023                54 non-null     float64
 40  RESIDUAL_2020                    53 non-null     float64
 41  RESIDUAL_2021                    53 non-null     float64
 42  RESIDUAL_2022                    53 non-null     float64
 43  RESIDUAL_2023                    53 non-null     float64
 44  R_BIRTH_2021                     53 non-null     float64
 45  R_BIRTH_2022                     53 non-null     float64
 46  R_BIRTH_2023                     53 non-null     float64
 47  R_DEATH_2021                     53 non-null     float64
 48  R_DEATH_2022                     53 non-null     float64
 49  R_DEATH_2023                     53 non-null     float64
 50  R_DOMESTIC_MIG_2021              53 non-null     float64
 51  R_DOMESTIC_MIG_2022              53 non-null     float64
 52  R_DOMESTIC_MIG_2023              53 non-null     float64
 53  R_INTERNATIONAL_MIG_2021         53 non-null     float64
 54  R_INTERNATIONAL_MIG_2022         53 non-null     float64
 55  R_INTERNATIONAL_MIG_2023         53 non-null     float64
 56  R_NATURAL_CHG_2021               53 non-null     float64
 57  R_NATURAL_CHG_2022               53 non-null     float64
 58  R_NATURAL_CHG_2023               53 non-null     float64
 59  R_NET_MIG_2021                   53 non-null     float64
 60  R_NET_MIG_2022                   53 non-null     float64
 61  R_NET_MIG_2023                   53 non-null     float64
 62  Rural_Urban_Continuum_Code_2013  1 non-null      float64
 63  Rural_Urban_Continuum_Code_2023  1 non-null      float64
 64  Urban_Influence_2013             1 non-null      float64
dtypes: float64(65)
memory usage: 35.2+ KB

In [7]:
data1_wide.dropna(thresh=40, axis=1, inplace=True)
data1_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54 entries, (0, 'US', 'United States') to (72000, 'PR', 'Puerto Rico')
Data columns (total 61 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   BIRTHS_2020               53 non-null     float64
 1   BIRTHS_2021               53 non-null     float64
 2   BIRTHS_2022               53 non-null     float64
 3   BIRTHS_2023               53 non-null     float64
 4   CENSUS_2020_POP           54 non-null     float64
 5   DEATHS_2020               53 non-null     float64
 6   DEATHS_2021               53 non-null     float64
 7   DEATHS_2022               53 non-null     float64
 8   DEATHS_2023               53 non-null     float64
 9   DOMESTIC_MIG_2020         53 non-null     float64
 10  DOMESTIC_MIG_2021         53 non-null     float64
 11  DOMESTIC_MIG_2022         53 non-null     float64
 12  DOMESTIC_MIG_2023         53 non-null     float64
 13  ESTIMATES_BASE_2020       54 non-null     float64
 14  GQ_ESTIMATES_2020         52 non-null     float64
 15  GQ_ESTIMATES_2021         52 non-null     float64
 16  GQ_ESTIMATES_2022         52 non-null     float64
 17  GQ_ESTIMATES_2023         52 non-null     float64
 18  GQ_ESTIMATES_BASE_2020    52 non-null     float64
 19  INTERNATIONAL_MIG_2020    53 non-null     float64
 20  INTERNATIONAL_MIG_2021    53 non-null     float64
 21  INTERNATIONAL_MIG_2022    53 non-null     float64
 22  INTERNATIONAL_MIG_2023    53 non-null     float64
 23  NATURAL_CHG_2020          53 non-null     float64
 24  NATURAL_CHG_2021          53 non-null     float64
 25  NATURAL_CHG_2022          53 non-null     float64
 26  NATURAL_CHG_2023          53 non-null     float64
 27  NET_MIG_2020              53 non-null     float64
 28  NET_MIG_2021              53 non-null     float64
 29  NET_MIG_2022              53 non-null     float64
 30  NET_MIG_2023              53 non-null     float64
 31  N_POP_CHG_2020            53 non-null     float64
 32  N_POP_CHG_2021            53 non-null     float64
 33  N_POP_CHG_2022            53 non-null     float64
 34  N_POP_CHG_2023            53 non-null     float64
 35  POP_ESTIMATE_2020         54 non-null     float64
 36  POP_ESTIMATE_2021         54 non-null     float64
 37  POP_ESTIMATE_2022         54 non-null     float64
 38  POP_ESTIMATE_2023         54 non-null     float64
 39  RESIDUAL_2020             53 non-null     float64
 40  RESIDUAL_2021             53 non-null     float64
 41  RESIDUAL_2022             53 non-null     float64
 42  RESIDUAL_2023             53 non-null     float64
 43  R_BIRTH_2021              53 non-null     float64
 44  R_BIRTH_2022              53 non-null     float64
 45  R_BIRTH_2023              53 non-null     float64
 46  R_DEATH_2021              53 non-null     float64
 47  R_DEATH_2022              53 non-null     float64
 48  R_DEATH_2023              53 non-null     float64
 49  R_DOMESTIC_MIG_2021       53 non-null     float64
 50  R_DOMESTIC_MIG_2022       53 non-null     float64
 51  R_DOMESTIC_MIG_2023       53 non-null     float64
 52  R_INTERNATIONAL_MIG_2021  53 non-null     float64
 53  R_INTERNATIONAL_MIG_2022  53 non-null     float64
 54  R_INTERNATIONAL_MIG_2023  53 non-null     float64
 55  R_NATURAL_CHG_2021        53 non-null     float64
 56  R_NATURAL_CHG_2022        53 non-null     float64
 57  R_NATURAL_CHG_2023        53 non-null     float64
 58  R_NET_MIG_2021            53 non-null     float64
 59  R_NET_MIG_2022            53 non-null     float64
 60  R_NET_MIG_2023            53 non-null     float64
dtypes: float64(61)
memory usage: 33.5+ KB

In [8]:
data1_wide.fillna(value=0, inplace=True)
data1_wide

,,Attribute,BIRTHS_2020,BIRTHS_2021,BIRTHS_2022,BIRTHS_2023,CENSUS_2020_POP,DEATHS_2020,DEATHS_2021,DEATHS_2022,DEATHS_2023,DOMESTIC_MIG_2020,...,R_DOMESTIC_MIG_2023,R_INTERNATIONAL_MIG_2021,R_INTERNATIONAL_MIG_2022,R_INTERNATIONAL_MIG_2023,R_NATURAL_CHG_2021,R_NATURAL_CHG_2022,R_NATURAL_CHG_2023,R_NET_MIG_2021,R_NET_MIG_2022,R_NET_MIG_2023
FIPStxt,State,Area_Name,,,,,,,,,,,,,,,,,,,,,
0,US,United States,894123.0,3584459.0,3679254.0,3653356.0,331449281.0,852024.0,3438423.0,3456087.0,3148861.0,0.0,...,0.0,1.1,3.0,3.4,0.4,0.7,1.5,1.1,3.0,3.4
1000,AL,Alabama,13867.0,57184.0,58106.0,58251.0,5024279.0,15165.0,69135.0,67208.0,59813.0,9615.0,...,6.0,0.4,0.9,1.1,-2.4,-1.8,-0.3,5.9,6.5,7.1
2000,AK,Alaska,2406.0,9453.0,9356.0,9266.0,733391.0,1171.0,5330.0,6340.0,5581.0,-1663.0,...,-7.6,1.2,3.2,2.7,5.6,4.1,5.0,-2.8,-6.6,-4.8
4000,AZ,Arizona,18110.0,75693.0,79137.0,78494.0,7151502.0,18025.0,80276.0,79807.0,70792.0,29980.0,...,4.9,1.1,3.0,2.9,-0.6,-0.1,1.0,12.5,12.6,7.8
5000,AR,Arkansas,8509.0,34927.0,36298.0,35566.0,3011524.0,8475.0,40180.0,40362.0,36473.0,2537.0,...,5.9,0.4,1.1,1.3,-1.7,-1.3,-0.3,6.3,7.3,7.3
6000,CA,California,103133.0,412506.0,423922.0,414120.0,39538223.0,74587.0,345181.0,318145.0,302704.0,-67932.0,...,-8.7,1.1,3.2,3.9,1.7,2.7,2.9,-10.5,-5.3,-4.8
8000,CO,Colorado,15593.0,62137.0,62682.0,62498.0,5773714.0,11914.0,46481.0,49599.0,45099.0,7169.0,...,1.2,0.7,1.8,2.0,2.7,2.2,3.0,1.6,2.9,3.3
9000,CT,Connecticut,8465.0,33942.0,35572.0,34957.0,3605944.0,11938.0,34571.0,34833.0,32842.0,-21420.0,...,-2.5,1.7,4.3,4.2,-0.2,0.2,0.6,7.0,1.5,1.7
10000,DE,Delaware,2579.0,10174.0,10883.0,10725.0,989948.0,2959.0,11228.0,11488.0,10897.0,2195.0,...,10.1,0.9,2.3,2.2,-1.1,-0.6,-0.2,14.2,14.9,12.3
11000,DC,District of Columbia,2187.0,8508.0,8399.0,7627.0,689545.0,2004.0,5837.0,5572.0,5020.0,-15475.0,...,-2.2,2.6,6.8,10.3,4.0,4.2,3.9,-7.2,-0.6,8.1
11001,DC,District of Columbia,2187.0,8508.0,8399.0,7627.0,689545.0,2004.0,5837.0,5572.0,5020.0,-15475.0,...,-2.2,2.6,6.8,10.3,4.0,4.2,3.9,-7.2,-0.6,8.1
12000,FL,Florida,50294.0,207942.0,222003.0,223578.0,21538187.0,56383.0,250389.0,260220.0,231181.0,61782.0,...,8.7,2.2,5.5,8.0,-2.0,-1.7,-0.3,13.4,19.9,16.6
13000,GA,Georgia,29847.0,121276.0,125599.0,125664.0,10711908.0,24771.0,109501.0,110380.0,97847.0,11606.0,...,5.3,0.9,2.5,2.7,1.1,1.4,2.5,4.2,9.9,8.1
15000,HI,Hawaii,3836.0,15528.0,15746.0,15167.0,1455271.0,2843.0,12152.0,13375.0,12812.0,-4831.0,...,-7.8,1.4,4.1,3.2,2.3,1.6,1.6,-5.5,-6.8,-4.6
16000,ID,Idaho,5467.0,21850.0,22418.0,22456.0,1839106.0,3629.0,17141.0,18938.0,16817.0,8814.0,...,7.9,0.4,0.9,2.4,2.5,1.8,2.9,27.8,15.8,10.3
17000,IL,Illinois,33452.0,131888.0,129614.0,127235.0,12812508.0,35296.0,128385.0,127064.0,116782.0,-22545.0,...,-6.7,0.9,2.5,3.2,0.3,0.2,0.8,-8.2,-8.8,-3.4
18000,IN,Indiana,19436.0,77712.0,80234.0,79587.0,6785528.0,19149.0,77868.0,79739.0,72079.0,1596.0,...,0.7,0.9,2.3,2.6,0.0,0.1,1.1,3.3,3.0,3.3
19000,IA,Iowa,9104.0,35887.0,36848.0,36898.0,3190369.0,8036.0,35499.0,35708.0,33119.0,-1270.0,...,-1.1,1.2,2.9,2.2,0.1,0.4,1.2,1.7,0.4,1.1
20000,KS,Kansas,8510.0,34168.0,34547.0,34768.0,2937880.0,6984.0,32824.0,33274.0,30329.0,-1920.0,...,-1.6,0.7,1.9,1.3,0.5,0.4,1.5,-1.0,-0.5,-0.2
21000,KY,Kentucky,12579.0,51364.0,52384.0,52380.0,4505836.0,12785.0,58401.0,61410.0,54385.0,1010.0,...,2.0,0.4,1.0,1.7,-1.6,-2.0,-0.4,1.1,3.1,3.7
22000,LA,Louisiana,13555.0,57028.0,56541.0,56209.0,4657757.0,14807.0,56872.0,56876.0,50094.0,-5154.0,...,-6.5,0.7,1.8,2.0,0.0,-0.1,1.3,-5.4,-8.5,-4.5
23000,ME,Maine,2997.0,11590.0,12009.0,11945.0,1362359.0,3704.0,16116.0,17977.0,16998.0,1803.0,...,6.6,0.7,1.8,1.6,-3.3,-4.3,-3.6,13.8,11.8,8.2
24000,MD,Maryland,17156.0,67431.0,68904.0,67969.0,6177224.0,16929.0,58995.0,57559.0,53770.0,-5257.0,...,-5.0,1.5,3.8,5.3,1.4,1.8,2.3,-1.4,-3.6,0.3
25000,MA,Massachusetts,17113.0,66441.0,69069.0,68387.0,7029917.0,22133.0,61652.0,63566.0,61404.0,-27235.0,...,-5.6,2.4,6.1,7.2,0.7,0.8,1.0,-1.4,-2.0,1.6
26000,MI,Michigan,26588.0,102799.0,104411.0,101911.0,10077331.0,31057.0,115214.0,117927.0,105941.0,-4859.0,...,-1.5,0.7,1.9,2.3,-1.2,-1.3,-0.4,-2.3,1.0,0.8
27000,MN,Minnesota,16461.0,63012.0,64630.0,63754.0,5706494.0,12746.0,51396.0,53436.0,49911.0,-1510.0,...,-0.8,1.0,2.5,2.5,2.0,2.0,2.4,-0.9,-2.6,1.7
28000,MS,Mississippi,8503.0,35004.0,34786.0,34628.0,2961279.0,9676.0,41703.0,40733.0,36032.0,-2122.0,...,-0.9,0.2,0.5,1.6,-2.3,-2.0,-0.5,-1.0,-1.4,0.7
29000,MO,Missouri,17239.0,68820.0,68857.0,68334.0,6154913.0,16745.0,75365.0,75735.0,68389.0,-1291.0,...,1.8,0.6,1.6,1.3,-1.1,-1.1,0.0,3.4,2.4,3.1
30000,MT,Montana,2812.0,10841.0,11219.0,11206.0,1084225.0,2518.0,12151.0,12896.0,11377.0,2746.0,...,8.4,0.6,1.6,0.5,-1.2,-1.5,-0.2,19.2,15.8,8.9
31000,NE,Nebraska,6046.0,24410.0,24174.0,24195.0,1961504.0,4462.0,19570.0,19473.0,18496.0,-778.0,...,-0.4,0.8,2.1,2.8,2.5,2.4,2.9,-2.3,-0.2,2.3
32000,NV,Nevada,8167.0,33361.0,33542.0,33055.0,3104614.0,7009.0,32390.0,33435.0,29322.0,10289.0,...,2.7,1.2,3.2,1.3,0.3,0.0,1.2,9.3,9.7,4.1
33000,NH,New Hampshire,2994.0,12044.0,12332.0,12155.0,1377529.0,3481.0,13709.0,14674.0,14264.0,1272.0,...,3.1,1.1,2.8,0.6,-1.2,-1.7,-1.5,7.2,10.0,3.7
34000,NJ,New Jersey,24722.0,98001.0,102468.0,102055.0,9288994.0,33966.0,83971.0,82566.0,76563.0,-9361.0,...,-4.8,1.6,4.2,5.3,1.5,2.1,2.7,-2.0,-2.9,0.5
35000,NM,New Mexico,5327.0,21433.0,21151.0,20728.0,2117522.0,5523.0,24640.0,25470.0,22344.0,702.0,...,-0.5,1.1,2.8,1.7,-1.5,-2.0,-0.8,0.5,0.6,1.2
36000,NY,New York,53056.0,205414.0,210106.0,207450.0,20201249.0,72698.0,177088.0,176382.0,165914.0,-72398.0,...,-11.0,1.4,3.9,3.8,1.4,1.7,2.1,-13.3,-11.2,-7.3
37000,NC,North Carolina,28675.0,116747.0,121639.0,121148.0,10439388.0,25861.0,115480.0,117926.0,108491.0,12492.0,...,9.0,0.9,2.5,2.7,0.1,0.3,1.2,10.6,11.7,11.8
38000,ND,North Dakota,2563.0,10019.0,9839.0,9649.0,779094.0,1751.0,7766.0,7390.0,6945.0,-448.0,...,0.0,0.6,1.6,2.9,2.9,3.1,3.5,-4.6,-1.9,2.9
39000,OH,Ohio,32340.0,128271.0,128796.0,128826.0,11799448.0,33762.0,146812.0,149079.0,131288.0,-2867.0,...,0.1,0.8,2.0,2.4,-1.6,-1.7,-0.2,-1.6,1.6,2.4
40000,OK,Oklahoma,11579.0,47473.0,48121.0,48073.0,3959353.0,10353.0,50805.0,51669.0,45506.0,3825.0,...,5.8,0.5,1.4,2.1,-0.8,-0.9,0.6,7.2,8.0,7.9
41000,OR,Oregon,10281.0,39660.0,40521.0,39046.0,4237256.0,9546.0,41943.0,46369.0,43285.0,6407.0,...,-1.4,0.6,1.7,1.0,-0.5,-1.4,-1.0,3.0,-2.4,-0.4
42000,PA,Pennsylvania,32903.0,130245.0,131600.0,129489.0,13002700.0,40289.0,155661.0,155062.0,140568.0,-3696.0,...,-1.9,0.8,2.0,2.0,-2.0,-1.8,-0.9,2.9,-1.1,0.1
44000,RI,Rhode Island,2546.0,10030.0,10386.0,10006.0,1097379.0,3389.0,11332.0,11078.0,10434.0,-430.0,...,-2.9,1.0,2.4,5.3,-1.2,-0.6,-0.4,1.3,-2.0,2.3
45000,SC,South Carolina,13492.0,55815.0,57508.0,57581.0,5118425.0,14065.0,64911.0,64636.0,58852.0,14724.0,...,15.5,0.8,2.0,1.7,-1.8,-1.4,-0.2,13.8,17.9,17.2
46000,SD,South Dakota,2832.0,11063.0,11324.0,11369.0,886667.0,2020.0,9779.0,9226.0,8556.0,299.0,...,5.3,1.2,3.1,2.0,1.4,2.3,3.1,8.0,12.4,7.2
47000,TN,Tennessee,19250.0,79463.0,82053.0,82244.0,6910840.0,18931.0,89405.0,91616.0,81216.0,14621.0,...,8.9,0.4,1.1,1.8,-1.4,-1.4,0.1,7.0,13.1,10.8
48000,TX,Texas,88268.0,364918.0,384024.0,390494.0,29145505.0,55732.0,270419.0,261745.0,232241.0,52914.0,...,6.2,1.5,3.9,4.2,3.2,4.1,5.2,8.0,11.5,10.4
49000,UT,Utah,11862.0,45703.0,46371.0,45965.0,3271616.0,4964.0,21993.0,23370.0,21169.0,4636.0,...,0.4,0.6,1.6,3.0,7.2,6.8,7.3,9.6,5.7,3.4
50000,VT,Vermont,1303.0,5153.0,5385.0,5072.0,643077.0,1565.0,6447.0,7216.0,6876.0,-66.0,...,1.3,0.6,1.6,2.0,-2.0,-2.8,-2.8,8.2,3.3,3.3
51000,VA,Virginia,23580.0,94275.0,96018.0,95669.0,8631393.0,19723.0,83763.0,86329.0,79980.0,-31.0,...,-0.8,1.7,4.3,3.2,1.2,1.1,1.8,1.0,1.4,2.4
53000,WA,Washington,21105.0,82602.0,83874.0,82523.0,7705281.0,15173.0,64924.0,70848.0,67663.0,11889.0,...,-2.0,1.8,4.8,3.7,2.3,1.7,1.9,-0.2,4.2,1.7
54000,WV,West Virginia,4296.0,17056.0,17100.0,17263.0,1793716.0,5871.0,27613.0,30006.0,25929.0,-813.0,...,2.0,0.4,1.0,0.6,-5.9,-7.3,-4.9,2.0,1.2,2.7
55000,WI,Wisconsin,15554.0,60034.0,60702.0,59839.0,5893718.0,14171.0,61983.0,63601.0,58692.0,13.0,...,1.0,0.5,1.3,2.3,-0.3,-0.5,0.2,-2.7,2.6,3.3
56000,WY,Wyoming,1584.0,6164.0,6046.0,5882.0,576851.0,1290.0,6176.0,6754.0,5779.0,436.0,...,3.5,0.2,0.6,0.6,0.0,-1.2,0.2,3.3,4.9,4.0
72000,PR,Puerto Rico,0.0,0.0,0.0,0.0,3285874.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Data File 2 dataframe
Here we will load the data_file_2 example data, then pivot and clean it in preparation for merging with the other two selected sample files.

For your submission you will adjust the code to reflect your selected dataset.

In [9]:
data2 = pd.read_csv(data_file_2)
data2.head()

,FIPS Code,State,Area name,Attribute,Value
0,0,US,United States,"Less than high school graduate, 2019-23",2.423022e+07
1,0,US,United States,"High school graduate (or equivalency), 2019-23",5.983649e+07
2,0,US,United States,"Some college or associate degree, 2019-23",6.441365e+07
3,0,US,United States,"Bachelor's degree or higher, 2019-23",7.995430e+07
4,0,US,United States,Percent of adults who are not high school grad...,1.060707e+01

In [10]:
data2.rename(columns={'Area name': 'Area_Name', 'FIPS Code': 'FIPStxt'}, inplace=True)
data2.head()

,FIPStxt,State,Area_Name,Attribute,Value
0,0,US,United States,"Less than high school graduate, 2019-23",2.423022e+07
1,0,US,United States,"High school graduate (or equivalency), 2019-23",5.983649e+07
2,0,US,United States,"Some college or associate degree, 2019-23",6.441365e+07
3,0,US,United States,"Bachelor's degree or higher, 2019-23",7.995430e+07
4,0,US,United States,Percent of adults who are not high school grad...,1.060707e+01

In [11]:
data2_wide = data2.pivot(index=['FIPStxt','State','Area_Name'], columns='Attribute', values='Value')
data2_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54 entries, (0, 'US', 'United States') to (72000, 'PR', 'Puerto Rico')
Data columns (total 8 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   Bachelor's degree or higher, 2019-23                                      54 non-null     float64
 1   High school graduate (or equivalency), 2019-23                            54 non-null     float64
 2   Less than high school graduate, 2019-23                                   54 non-null     float64
 3   Percent of adults completing some college or associate degree, 2019-23    54 non-null     float64
 4   Percent of adults who are high school graduates (or equivalent), 2019-23  54 non-null     float64
 5   Percent of adults who are not high school graduates, 2019-23              54 non-null     float64
 6   Percent of adults with a bachelor's degree or higher, 2019-23             54 non-null     float64
 7   Some college or associate degree, 2019-23                                 54 non-null     float64
dtypes: float64(8)
memory usage: 11.1+ KB

In [12]:
data2_wide

,,Attribute,"Bachelor's degree or higher, 2019-23","High school graduate (or equivalency), 2019-23","Less than high school graduate, 2019-23","Percent of adults completing some college or associate degree, 2019-23","Percent of adults who are high school graduates (or equivalent), 2019-23","Percent of adults who are not high school graduates, 2019-23","Percent of adults with a bachelor's degree or higher, 2019-23","Some college or associate degree, 2019-23"
FIPStxt,State,Area_Name,,,,,,,,
0,US,United States,79954302.0,59836489.0,24230217.0,28.197846,26.194137,10.607067,35.000950,64413653.0
1000,AL,Alabama,957081.0,1046374.0,409381.0,30.028286,30.344616,11.871959,27.755139,1035466.0
2000,AK,Alaska,152432.0,141206.0,31854.0,33.287559,28.941408,6.528757,31.242276,162411.0
4000,AZ,Arizona,1627462.0,1171693.0,544528.0,33.000824,23.477843,10.911001,32.610332,1646950.0
5000,AR,Arkansas,513221.0,702778.0,233857.0,29.060040,34.386203,11.442382,25.111375,593923.0
6000,CA,California,9834361.0,5496195.0,4149146.0,27.695487,20.400707,15.400748,36.503058,7461496.0
8000,CO,Colorado,1806355.0,811023.0,292446.0,27.948508,20.082114,7.241390,44.727988,1128710.0
9000,CT,Connecticut,1062403.0,647094.0,219549.0,23.839007,25.548028,8.668051,41.944913,603807.0
10000,DE,Delaware,250626.0,206192.0,61144.0,27.092993,29.023059,8.606473,35.277475,192480.0
11000,DC,District of Columbia,307906.0,70322.0,34651.0,14.765920,14.517161,7.153297,63.563622,71527.0
11001,DC,District of Columbia,307906.0,70322.0,34651.0,14.765920,14.517161,7.153297,63.563622,71527.0
12000,FL,Florida,5263931.0,4346402.0,1643437.0,28.999636,27.421577,10.368492,33.210295,4596529.0
13000,GA,Georgia,2480907.0,1950698.0,801324.0,27.852120,26.894828,11.048082,34.204970,2020131.0
15000,HI,Hawaii,364398.0,273812.0,72950.0,30.777310,26.652235,7.100786,35.469669,316191.0
16000,ID,Idaho,388032.0,322573.0,103570.0,34.568627,25.923658,8.323428,31.184286,430144.0
17000,IL,Illinois,3249494.0,2207546.0,851323.0,27.810428,25.261990,9.742090,37.185492,2430244.0
18000,IN,Indiana,1313086.0,1496214.0,445651.0,28.608599,32.816719,9.774540,28.800141,1304353.0
19000,IA,Iowa,660619.0,649969.0,145119.0,31.991436,30.365629,6.779754,30.863182,684769.0
20000,KS,Kansas,679664.0,495115.0,156595.0,31.134391,25.609931,8.099910,35.155768,601919.0
21000,KY,Kentucky,830856.0,1006715.0,352966.0,28.836086,32.705122,11.466797,26.991996,887620.0
22000,LA,Louisiana,825794.0,1012121.0,407400.0,27.809272,32.541426,13.098609,26.550693,864939.0
23000,ME,Maine,359323.0,310243.0,56031.0,28.627229,30.516806,5.511445,35.344521,291033.0
24000,MD,Maryland,1826045.0,1014175.0,382701.0,24.571447,23.735534,8.956652,42.736366,1049892.0
25000,MA,Massachusetts,2305899.0,1129802.0,425209.0,21.932898,22.844451,8.597671,46.624980,1084720.0
26000,MI,Michigan,2213104.0,1964538.0,564902.0,31.932879,28.195932,8.107727,31.763462,2224908.0
27000,MN,Minnesota,1513374.0,916744.0,239636.0,31.502441,23.520791,6.148312,38.828456,1227836.0
28000,MS,Mississippi,475997.0,589225.0,263266.0,32.574260,29.905375,13.361735,24.158630,641810.0
29000,MO,Missouri,1345230.0,1279442.0,354732.0,29.355020,30.336992,8.411090,31.896898,1238028.0
30000,MT,Montana,266066.0,214759.0,41822.0,32.153284,27.878650,5.429067,34.538999,247688.0
31000,NE,Nebraska,440234.0,324253.0,102256.0,32.823951,25.130904,7.925249,34.119896,423513.0
32000,NV,Nevada,601393.0,602478.0,277389.0,32.549847,27.434234,12.631091,27.384828,714821.0
33000,NH,New Hampshire,401838.0,272558.0,59997.0,27.231769,27.006744,5.944876,39.816611,274829.0
34000,NJ,New Jersey,2771686.0,1662983.0,600736.0,22.043141,25.745880,9.300442,42.910537,1423815.0
35000,NM,New Mexico,438228.0,373330.0,178146.0,31.791545,25.729170,12.277472,30.201813,461295.0
36000,NY,New York,5535503.0,3437438.0,1698537.0,23.754124,24.559904,12.135755,39.550217,3324660.0
37000,NC,North Carolina,2521353.0,1812528.0,744581.0,30.066168,24.959728,10.253380,34.720724,2183348.0
38000,ND,North Dakota,164378.0,130763.0,31418.0,35.861801,25.682659,6.170689,32.284852,182590.0
39000,OH,Ohio,2514129.0,2624935.0,680554.0,28.359331,32.313478,8.377757,30.949434,2303726.0
40000,OK,Oklahoma,733793.0,811387.0,287078.0,30.631104,30.718938,10.868712,27.781246,809067.0
41000,OR,Oregon,1094312.0,676182.0,250221.0,33.111277,22.382647,8.282694,36.223382,1000295.0
42000,PA,Pennsylvania,3157318.0,3039316.0,740736.0,24.207808,33.205152,8.092693,34.494348,2215776.0
44000,RI,Rhode Island,289667.0,205862.0,81676.0,25.666287,26.511355,10.518413,37.303945,199300.0
45000,SC,South Carolina,1136208.0,1019313.0,375697.0,29.890421,28.232892,10.406041,31.470645,1079156.0
46000,SD,South Dakota,185411.0,175713.0,41643.0,32.437175,29.475272,6.985475,31.102079,193370.0
47000,TN,Tennessee,1460501.0,1508292.0,499497.0,27.827153,31.386570,10.394206,30.392071,1337243.0
48000,TX,Texas,6381971.0,4691708.0,2759723.0,28.304397,24.316132,14.303062,33.076409,5461229.0
49000,UT,Utah,739555.0,449786.0,134602.0,33.904769,22.454675,6.719738,36.920818,679141.0
50000,VT,Vermont,197369.0,126179.0,25326.0,24.648593,27.252719,5.470026,42.628662,114122.0
51000,VA,Virginia,2471630.0,1423702.0,516186.0,25.967764,23.891967,8.662416,41.477853,1547397.0
53000,WA,Washington,2097154.0,1176403.0,421541.0,31.687972,21.748401,7.793114,38.770512,1714049.0
54000,WV,West Virginia,295541.0,501118.0,144554.0,25.842143,39.482919,11.389361,23.285576,327989.0
55000,WI,Wisconsin,1333128.0,1207407.0,269431.0,30.951992,29.669059,6.620605,32.758344,1259617.0
56000,WY,Wyoming,118336.0,109885.0,23502.0,36.353867,27.783537,5.942291,29.920304,143781.0
72000,PR,Puerto Rico,702653.0,670172.0,472462.0,23.497594,27.784172,19.587457,29.130778,566777.0

### Data File 3 dataframe
If you choose not to included a third file for merging, remove or comment out the blocks for data3.

Here we will load the data_file_3 example data, then pivot and clean it in preparation for merging with the other two selected sample files.

For your submission you will adjust the code to reflect your selected dataset.

In [13]:
data3 = pd.read_csv(data_file_3)
data3.head()

   FIPS_Code State      Area_Name                  Attribute        Value
0          0    US  United States  Civilian_labor_force_2019  163815894.0
1          0    US  United States              Employed_2019  157805901.0
2          0    US  United States            Unemployed_2019    6009993.0
3          0    US  United States     Unemployment_rate_2019          3.7
4          0    US  United States  Civilian_labor_force_2020  161131754.0

In [14]:
data3.rename(columns={'FIPS_Code': 'FIPStxt'}, inplace=True)
data3.head()

   FIPStxt State      Area_Name                  Attribute        Value
0        0    US  United States  Civilian_labor_force_2019  163815894.0
1        0    US  United States              Employed_2019  157805901.0
2        0    US  United States            Unemployed_2019    6009993.0
3        0    US  United States     Unemployment_rate_2019          3.7
4        0    US  United States  Civilian_labor_force_2020  161131754.0

In [15]:
data3_wide = data3.pivot(index=['FIPStxt','State','Area_Name'], columns='Attribute', values='Value')
data3_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54 entries, (0, 'US', 'United States') to (72000, 'PR', 'Puerto Rico')
Data columns (total 25 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Civilian_labor_force_2019                  54 non-null     float64
 1   Civilian_labor_force_2020                  53 non-null     float64
 2   Civilian_labor_force_2021                  54 non-null     float64
 3   Civilian_labor_force_2022                  54 non-null     float64
 4   Civilian_labor_force_2023                  54 non-null     float64
 5   Employed_2019                              54 non-null     float64
 6   Employed_2020                              53 non-null     float64
 7   Employed_2021                              54 non-null     float64
 8   Employed_2022                              54 non-null     float64
 9   Employed_2023                              54 non-null     float64
 10  Med_HH_Income_Percent_of_State_Total_2022  52 non-null     float64
 11  Median_Household_Income_2022               53 non-null     float64
 12  Metro_2023                                 1 non-null      float64
 13  Rural_Urban_Continuum_Code_2023            1 non-null      float64
 14  Unemployed_2019                            54 non-null     float64
 15  Unemployed_2020                            53 non-null     float64
 16  Unemployed_2021                            54 non-null     float64
 17  Unemployed_2022                            54 non-null     float64
 18  Unemployed_2023                            54 non-null     float64
 19  Unemployment_rate_2019                     54 non-null     float64
 20  Unemployment_rate_2020                     53 non-null     float64
 21  Unemployment_rate_2021                     54 non-null     float64
 22  Unemployment_rate_2022                     54 non-null     float64
 23  Unemployment_rate_2023                     54 non-null     float64
 24  Urban_Influence_Code_2013                  1 non-null      float64
dtypes: float64(25)
memory usage: 18.3+ KB

In [16]:
data3_wide.dropna(thresh=40, axis=1, inplace=True)
data3_wide.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 54 entries, (0, 'US', 'United States') to (72000, 'PR', 'Puerto Rico')
Data columns (total 22 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Civilian_labor_force_2019                  54 non-null     float64
 1   Civilian_labor_force_2020                  53 non-null     float64
 2   Civilian_labor_force_2021                  54 non-null     float64
 3   Civilian_labor_force_2022                  54 non-null     float64
 4   Civilian_labor_force_2023                  54 non-null     float64
 5   Employed_2019                              54 non-null     float64
 6   Employed_2020                              53 non-null     float64
 7   Employed_2021                              54 non-null     float64
 8   Employed_2022                              54 non-null     float64
 9   Employed_2023                              54 non-null     float64
 10  Med_HH_Income_Percent_of_State_Total_2022  52 non-null     float64
 11  Median_Household_Income_2022               53 non-null     float64
 12  Unemployed_2019                            54 non-null     float64
 13  Unemployed_2020                            53 non-null     float64
 14  Unemployed_2021                            54 non-null     float64
 15  Unemployed_2022                            54 non-null     float64
 16  Unemployed_2023                            54 non-null     float64
 17  Unemployment_rate_2019                     54 non-null     float64
 18  Unemployment_rate_2020                     53 non-null     float64
 19  Unemployment_rate_2021                     54 non-null     float64
 20  Unemployment_rate_2022                     54 non-null     float64
 21  Unemployment_rate_2023                     54 non-null     float64
dtypes: float64(22)
memory usage: 17.0+ KB

In [17]:
data3_wide.fillna(value=0, inplace=True)
data3_wide

,,Attribute,Civilian_labor_force_2019,Civilian_labor_force_2020,Civilian_labor_force_2021,Civilian_labor_force_2022,Civilian_labor_force_2023,Employed_2019,Employed_2020,Employed_2021,Employed_2022,Employed_2023,...,Unemployed_2019,Unemployed_2020,Unemployed_2021,Unemployed_2022,Unemployed_2023,Unemployment_rate_2019,Unemployment_rate_2020,Unemployment_rate_2021,Unemployment_rate_2022,Unemployment_rate_2023
FIPStxt,State,Area_Name,,,,,,,,,,,,,,,,,,,,,
0,US,United States,163815894.0,161131754.0,161784447.0,164341251.0,166689556.0,157805901.0,148133696.0,153122706.0,158342285.0,160623678.0,...,6009993.0,12998058.0,8661741.0,5998966.0,6065878.0,3.7,8.1,5.4,3.7,3.6
1000,AL,Alabama,2271835.0,2263144.0,2249514.0,2276362.0,2308131.0,2199379.0,2118600.0,2173978.0,2218627.0,2250472.0,...,72456.0,144544.0,75536.0,57735.0,57659.0,3.2,6.4,3.4,2.5,2.5
2000,AK,Alaska,352029.0,346552.0,351520.0,353692.0,357094.0,332197.0,317678.0,329147.0,338729.0,342005.0,...,19832.0,28874.0,22373.0,14963.0,15089.0,5.6,8.3,6.4,4.2,4.2
4000,AZ,Arizona,3432400.0,3471339.0,3525449.0,3599531.0,3690974.0,3267548.0,3200219.0,3347264.0,3462671.0,3546508.0,...,164852.0,271120.0,178185.0,136860.0,144466.0,4.8,7.8,5.1,3.8,3.9
5000,AR,Arkansas,1353175.0,1340557.0,1330676.0,1359540.0,1377657.0,1305858.0,1257949.0,1276933.0,1315886.0,1332876.0,...,47317.0,82608.0,53743.0,43654.0,44781.0,3.5,6.2,4.0,3.2,3.3
6000,CA,California,19385262.0,18958604.0,18956575.0,19169341.0,19308287.0,18589551.0,17037036.0,17568743.0,18348916.0,18388329.0,...,795711.0,1921568.0,1387832.0,820425.0,919958.0,4.1,10.1,7.3,4.3,4.8
8000,CO,Colorado,3104684.0,3082228.0,3149673.0,3186932.0,3230482.0,3022060.0,2873752.0,2977479.0,3089081.0,3128115.0,...,82624.0,208476.0,172194.0,97851.0,102367.0,2.7,6.8,5.5,3.1,3.2
9000,CT,Connecticut,1931826.0,1874247.0,1842166.0,1912008.0,1893200.0,1862314.0,1724812.0,1724540.0,1833670.0,1822088.0,...,69512.0,149435.0,117626.0,78338.0,71112.0,3.6,8.0,6.4,4.1,3.8
10000,DE,Delaware,485873.0,486701.0,493627.0,497202.0,506529.0,468539.0,450325.0,466623.0,475995.0,486404.0,...,17334.0,36376.0,27004.0,21207.0,20125.0,3.6,7.5,5.5,4.3,4.0
11000,DC,District of Columbia,400641.0,386235.0,377737.0,388387.0,398251.0,378443.0,355694.0,352029.0,369952.0,378714.0,...,22198.0,30541.0,25708.0,18435.0,19537.0,5.5,7.9,6.8,4.7,4.9
11001,DC,District of Columbia,400641.0,386235.0,377737.0,388387.0,398251.0,378443.0,355694.0,352029.0,369952.0,378714.0,...,22198.0,30541.0,25708.0,18435.0,19537.0,5.5,7.9,6.8,4.7,4.9
12000,FL,Florida,10256297.0,10077028.0,10320373.0,10692183.0,10988566.0,9922941.0,9257738.0,9838506.0,10370751.0,10668886.0,...,333356.0,819290.0,481867.0,321432.0,319680.0,3.3,8.1,4.7,3.0,2.9
13000,GA,Georgia,5165423.0,5082864.0,5156388.0,5222263.0,5305623.0,4980501.0,4754102.0,4954094.0,5058165.0,5135833.0,...,184922.0,328762.0,202294.0,164098.0,169790.0,3.6,6.5,3.9,3.1,3.2
15000,HI,Hawaii,686066.0,665964.0,670193.0,672727.0,676355.0,668769.0,588159.0,630151.0,650672.0,656336.0,...,17297.0,77805.0,40042.0,22055.0,20019.0,2.5,11.7,6.0,3.3,3.0
16000,ID,Idaho,888611.0,899807.0,921718.0,944919.0,961506.0,862940.0,850130.0,888950.0,918106.0,931748.0,...,25671.0,49677.0,32768.0,26813.0,29758.0,2.9,5.5,3.6,2.8,3.1
17000,IL,Illinois,6543691.0,6321066.0,6327675.0,6421708.0,6437855.0,6283464.0,5735263.0,5942191.0,6127480.0,6150672.0,...,260227.0,585803.0,385484.0,294228.0,287183.0,4.0,9.3,6.1,4.6,4.5
18000,IN,Indiana,3399870.0,3328778.0,3332745.0,3373887.0,3401387.0,3287462.0,3086279.0,3201829.0,3270662.0,3288017.0,...,112408.0,242499.0,130916.0,103225.0,113370.0,3.3,7.3,3.9,3.1,3.3
19000,IA,Iowa,1742078.0,1668401.0,1679982.0,1706493.0,1709402.0,1695474.0,1582202.0,1615303.0,1658263.0,1659106.0,...,46604.0,86199.0,64679.0,48230.0,50296.0,2.7,5.2,3.8,2.8,2.9
20000,KS,Kansas,1504415.0,1501827.0,1498226.0,1502603.0,1510988.0,1456662.0,1414596.0,1448294.0,1463010.0,1470936.0,...,47753.0,87231.0,49932.0,39593.0,40052.0,3.2,5.8,3.3,2.6,2.7
21000,KY,Kentucky,2064637.0,2005210.0,2010884.0,2030274.0,2026263.0,1979803.0,1874863.0,1921355.0,1948312.0,1941994.0,...,84834.0,130347.0,89529.0,81962.0,84269.0,4.1,6.5,4.5,4.0,4.2
22000,LA,Louisiana,2101749.0,2052043.0,2056137.0,2068817.0,2076760.0,2004115.0,1875244.0,1941271.0,1993244.0,2000152.0,...,97634.0,176799.0,114866.0,75573.0,76608.0,4.6,8.6,5.6,3.7,3.7
23000,ME,Maine,698261.0,671979.0,688542.0,681172.0,687322.0,678011.0,637985.0,656138.0,661833.0,667619.0,...,20250.0,33994.0,32404.0,19339.0,19703.0,2.9,5.1,4.7,2.8,2.9
24000,MD,Maryland,3338480.0,3230561.0,3152885.0,3154854.0,3184868.0,3225825.0,3022470.0,2988216.0,3060216.0,3117270.0,...,112655.0,208091.0,164669.0,94638.0,67598.0,3.4,6.4,5.2,3.0,2.1
25000,MA,Massachusetts,3848611.0,3744255.0,3731417.0,3743592.0,3751662.0,3731900.0,3396014.0,3530207.0,3606318.0,3625293.0,...,116711.0,348241.0,201210.0,137274.0,126369.0,3.0,9.3,5.4,3.7,3.4
26000,MI,Michigan,4979516.0,4861572.0,4775153.0,4866063.0,5007904.0,4776963.0,4376032.0,4500849.0,4664171.0,4812421.0,...,202553.0,485540.0,274304.0,201892.0,195483.0,4.1,10.0,5.7,4.1,3.9
27000,MN,Minnesota,3111674.0,3122016.0,3049037.0,3071450.0,3099923.0,3009672.0,2926644.0,2935653.0,2992787.0,3012707.0,...,102002.0,195372.0,113384.0,78663.0,87216.0,3.3,6.3,3.7,2.6,2.8
28000,MS,Mississippi,1278958.0,1244316.0,1251894.0,1248093.0,1231104.0,1208541.0,1145184.0,1183867.0,1200234.0,1192015.0,...,70417.0,99132.0,68027.0,47859.0,39089.0,5.5,8.0,5.4,3.8,3.2
29000,MO,Missouri,3073523.0,3025785.0,3028635.0,3036611.0,3087759.0,2973662.0,2839617.0,2902841.0,2957352.0,2993587.0,...,99861.0,186168.0,125794.0,79259.0,94172.0,3.2,6.2,4.2,2.6,3.0
30000,MT,Montana,543914.0,544500.0,549105.0,564052.0,574096.0,524870.0,512744.0,530391.0,548848.0,557509.0,...,19044.0,31756.0,18714.0,15204.0,16587.0,3.5,5.8,3.4,2.7,2.9
31000,NE,Nebraska,1050380.0,1045106.0,1043331.0,1050357.0,1054681.0,1017743.0,1000645.0,1015997.0,1027681.0,1030880.0,...,32637.0,44461.0,27334.0,22676.0,23801.0,3.1,4.3,2.6,2.2,2.3
32000,NV,Nevada,1545118.0,1505941.0,1500442.0,1557609.0,1602652.0,1481046.0,1302514.0,1397961.0,1476297.0,1520260.0,...,64072.0,203427.0,102481.0,81312.0,82392.0,4.1,13.5,6.8,5.2,5.1
33000,NH,New Hampshire,778467.0,761429.0,753206.0,760333.0,759604.0,758463.0,710538.0,727574.0,742975.0,742886.0,...,20004.0,50891.0,25632.0,17358.0,16718.0,2.6,6.7,3.4,2.3,2.2
34000,NJ,New Jersey,4687390.0,4638386.0,4648814.0,4736213.0,4829671.0,4525044.0,4200980.0,4337793.0,4552563.0,4615722.0,...,162346.0,437406.0,311021.0,183650.0,213949.0,3.5,9.4,6.7,3.9,4.4
35000,NM,New Mexico,955798.0,931499.0,942420.0,947411.0,965244.0,908397.0,858100.0,875911.0,908878.0,928983.0,...,47401.0,73399.0,66509.0,38533.0,36261.0,5.0,7.9,7.1,4.1,3.8
36000,NY,New York,9850900.0,9564414.0,9532961.0,9595770.0,9717791.0,9470443.0,8628006.0,8856999.0,9178585.0,9306973.0,...,380457.0,936408.0,675962.0,417185.0,410818.0,3.9,9.8,7.1,4.3,4.2
37000,NC,North Carolina,5000820.0,4831154.0,4939281.0,5155937.0,5231638.0,4807598.0,4483551.0,4697757.0,4965568.0,5050870.0,...,193222.0,347603.0,241524.0,190369.0,180768.0,3.9,7.2,4.9,3.7,3.5
38000,ND,North Dakota,414120.0,409175.0,407443.0,412237.0,416722.0,405150.0,388962.0,395160.0,403886.0,408909.0,...,8970.0,20213.0,12283.0,8351.0,7813.0,2.2,4.9,3.0,2.0,1.9
39000,OH,Ohio,5879395.0,5736620.0,5708982.0,5733131.0,5786996.0,5634934.0,5266859.0,5415608.0,5503265.0,5582438.0,...,244461.0,469761.0,293374.0,229866.0,204558.0,4.2,8.2,5.1,4.0,3.5
40000,OK,Oklahoma,1843331.0,1842829.0,1866370.0,1903508.0,1963240.0,1785400.0,1726786.0,1791369.0,1845328.0,1899949.0,...,57931.0,116043.0,75001.0,58180.0,63291.0,3.1,6.3,4.0,3.1,3.2
41000,OR,Oregon,2091454.0,2107241.0,2144461.0,2159953.0,2162127.0,2013835.0,1947540.0,2033502.0,2075083.0,2081652.0,...,77619.0,159701.0,110959.0,84870.0,80475.0,3.7,7.6,5.2,3.9,3.7
42000,PA,Pennsylvania,6576454.0,6506484.0,6431855.0,6465248.0,6518343.0,6291680.0,5929949.0,6054068.0,6202046.0,6295653.0,...,284774.0,576535.0,377787.0,263202.0,222690.0,4.3,8.9,5.9,4.1,3.4
44000,RI,Rhode Island,574066.0,570736.0,572546.0,571754.0,573848.0,553845.0,518282.0,540926.0,553588.0,556609.0,...,20221.0,52454.0,31620.0,18166.0,17239.0,3.5,9.2,5.5,3.2,3.0
45000,SC,South Carolina,2333533.0,2339140.0,2359169.0,2393329.0,2453060.0,2268884.0,2199751.0,2266611.0,2316435.0,2380392.0,...,64649.0,139389.0,92558.0,76894.0,72668.0,2.8,6.0,3.9,3.2,3.0
46000,SD,South Dakota,464665.0,464293.0,468876.0,474514.0,480238.0,451735.0,444895.0,456631.0,464946.0,470715.0,...,12930.0,19398.0,12245.0,9568.0,9523.0,2.8,4.2,2.6,2.0,2.0
47000,TN,Tennessee,3339445.0,3299159.0,3321355.0,3361979.0,3379605.0,3227700.0,3053560.0,3172858.0,3247975.0,3267935.0,...,111745.0,245599.0,148497.0,114004.0,111670.0,3.3,7.4,4.5,3.4,3.3
48000,TX,Texas,13927670.0,13941490.0,14292315.0,14672312.0,15067153.0,13434744.0,12872070.0,13486624.0,14093906.0,14472524.0,...,492926.0,1069420.0,805691.0,578406.0,594629.0,3.5,7.7,5.6,3.9,3.9
49000,UT,Utah,1619079.0,1644201.0,1683325.0,1737741.0,1790381.0,1577970.0,1564747.0,1636957.0,1696513.0,1743223.0,...,41109.0,79454.0,46368.0,41228.0,47158.0,2.5,4.8,2.8,2.4,2.6
50000,VT,Vermont,353432.0,339758.0,336265.0,343550.0,350886.0,346059.0,320708.0,324166.0,335547.0,343840.0,...,7373.0,19050.0,12099.0,8003.0,7046.0,2.1,5.6,3.6,2.3,2.0
51000,VA,Virginia,4419378.0,4332338.0,4315045.0,4427292.0,4555208.0,4297265.0,4053387.0,4148175.0,4304759.0,4424155.0,...,122113.0,278951.0,166870.0,122533.0,131053.0,2.8,6.4,3.9,2.8,2.9
53000,WA,Washington,3960885.0,3891363.0,3869163.0,3969967.0,4025762.0,3794004.0,3560168.0,3667123.0,3806848.0,3860883.0,...,166881.0,331195.0,202040.0,163119.0,164879.0,4.2,8.5,5.2,4.1,4.1
54000,WV,West Virginia,794874.0,777139.0,773616.0,778705.0,785642.0,755523.0,713044.0,733825.0,748269.0,754986.0,...,39351.0,64095.0,39791.0,30436.0,30656.0,5.0,8.2,5.1,3.9,3.9
55000,WI,Wisconsin,3117744.0,3100674.0,3106511.0,3094981.0,3133909.0,3017904.0,2900956.0,2986636.0,3004778.0,3038960.0,...,99840.0,199718.0,119875.0,90203.0,94949.0,3.2,6.4,3.9,2.9,3.0
56000,WY,Wyoming,293997.0,293606.0,288769.0,292664.0,295207.0,283071.0,276367.0,275633.0,282615.0,286669.0,...,10926.0,17239.0,13136.0,10049.0,8538.0,3.7,5.9,4.5,3.4,2.9
72000,PR,Puerto Rico,1090852.0,0.0,1171949.0,1187414.0,1197463.0,1000363.0,0.0,1079112.0,1115938.0,1127126.0,...,90489.0,0.0,92837.0,71476.0,70337.0,8.3,0.0,7.9,6.0,5.9

### Data Merging
Here is the example of a merge of the three sample files. You will need to adjust these blocks for how you wish to merge your selected data files.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you need merge your dataset.</span>
</div>

In [18]:
merged_data_1_2 = pd.merge(data1_wide, data2_wide, on=['FIPStxt', 'State', 'Area_Name'])
merged_data_1_2

,,Attribute,BIRTHS_2020,BIRTHS_2021,BIRTHS_2022,BIRTHS_2023,CENSUS_2020_POP,DEATHS_2020,DEATHS_2021,DEATHS_2022,DEATHS_2023,DOMESTIC_MIG_2020,...,R_NET_MIG_2022,R_NET_MIG_2023,"Bachelor's degree or higher, 2019-23","High school graduate (or equivalency), 2019-23","Less than high school graduate, 2019-23","Percent of adults completing some college or associate degree, 2019-23","Percent of adults who are high school graduates (or equivalent), 2019-23","Percent of adults who are not high school graduates, 2019-23","Percent of adults with a bachelor's degree or higher, 2019-23","Some college or associate degree, 2019-23"
FIPStxt,State,Area_Name,,,,,,,,,,,,,,,,,,,,,
0,US,United States,894123.0,3584459.0,3679254.0,3653356.0,331449281.0,852024.0,3438423.0,3456087.0,3148861.0,0.0,...,3.0,3.4,79954302.0,59836489.0,24230217.0,28.197846,26.194137,10.607067,35.000950,64413653.0
1000,AL,Alabama,13867.0,57184.0,58106.0,58251.0,5024279.0,15165.0,69135.0,67208.0,59813.0,9615.0,...,6.5,7.1,957081.0,1046374.0,409381.0,30.028286,30.344616,11.871959,27.755139,1035466.0
2000,AK,Alaska,2406.0,9453.0,9356.0,9266.0,733391.0,1171.0,5330.0,6340.0,5581.0,-1663.0,...,-6.6,-4.8,152432.0,141206.0,31854.0,33.287559,28.941408,6.528757,31.242276,162411.0
4000,AZ,Arizona,18110.0,75693.0,79137.0,78494.0,7151502.0,18025.0,80276.0,79807.0,70792.0,29980.0,...,12.6,7.8,1627462.0,1171693.0,544528.0,33.000824,23.477843,10.911001,32.610332,1646950.0
5000,AR,Arkansas,8509.0,34927.0,36298.0,35566.0,3011524.0,8475.0,40180.0,40362.0,36473.0,2537.0,...,7.3,7.3,513221.0,702778.0,233857.0,29.060040,34.386203,11.442382,25.111375,593923.0
6000,CA,California,103133.0,412506.0,423922.0,414120.0,39538223.0,74587.0,345181.0,318145.0,302704.0,-67932.0,...,-5.3,-4.8,9834361.0,5496195.0,4149146.0,27.695487,20.400707,15.400748,36.503058,7461496.0
8000,CO,Colorado,15593.0,62137.0,62682.0,62498.0,5773714.0,11914.0,46481.0,49599.0,45099.0,7169.0,...,2.9,3.3,1806355.0,811023.0,292446.0,27.948508,20.082114,7.241390,44.727988,1128710.0
9000,CT,Connecticut,8465.0,33942.0,35572.0,34957.0,3605944.0,11938.0,34571.0,34833.0,32842.0,-21420.0,...,1.5,1.7,1062403.0,647094.0,219549.0,23.839007,25.548028,8.668051,41.944913,603807.0
10000,DE,Delaware,2579.0,10174.0,10883.0,10725.0,989948.0,2959.0,11228.0,11488.0,10897.0,2195.0,...,14.9,12.3,250626.0,206192.0,61144.0,27.092993,29.023059,8.606473,35.277475,192480.0
11000,DC,District of Columbia,2187.0,8508.0,8399.0,7627.0,689545.0,2004.0,5837.0,5572.0,5020.0,-15475.0,...,-0.6,8.1,307906.0,70322.0,34651.0,14.765920,14.517161,7.153297,63.563622,71527.0
11001,DC,District of Columbia,2187.0,8508.0,8399.0,7627.0,689545.0,2004.0,5837.0,5572.0,5020.0,-15475.0,...,-0.6,8.1,307906.0,70322.0,34651.0,14.765920,14.517161,7.153297,63.563622,71527.0
12000,FL,Florida,50294.0,207942.0,222003.0,223578.0,21538187.0,56383.0,250389.0,260220.0,231181.0,61782.0,...,19.9,16.6,5263931.0,4346402.0,1643437.0,28.999636,27.421577,10.368492,33.210295,4596529.0
13000,GA,Georgia,29847.0,121276.0,125599.0,125664.0,10711908.0,24771.0,109501.0,110380.0,97847.0,11606.0,...,9.9,8.1,2480907.0,1950698.0,801324.0,27.852120,26.894828,11.048082,34.204970,2020131.0
15000,HI,Hawaii,3836.0,15528.0,15746.0,15167.0,1455271.0,2843.0,12152.0,13375.0,12812.0,-4831.0,...,-6.8,-4.6,364398.0,273812.0,72950.0,30.777310,26.652235,7.100786,35.469669,316191.0
16000,ID,Idaho,5467.0,21850.0,22418.0,22456.0,1839106.0,3629.0,17141.0,18938.0,16817.0,8814.0,...,15.8,10.3,388032.0,322573.0,103570.0,34.568627,25.923658,8.323428,31.184286,430144.0
17000,IL,Illinois,33452.0,131888.0,129614.0,127235.0,12812508.0,35296.0,128385.0,127064.0,116782.0,-22545.0,...,-8.8,-3.4,3249494.0,2207546.0,851323.0,27.810428,25.261990,9.742090,37.185492,2430244.0
18000,IN,Indiana,19436.0,77712.0,80234.0,79587.0,6785528.0,19149.0,77868.0,79739.0,72079.0,1596.0,...,3.0,3.3,1313086.0,1496214.0,445651.0,28.608599,32.816719,9.774540,28.800141,1304353.0
19000,IA,Iowa,9104.0,35887.0,36848.0,36898.0,3190369.0,8036.0,35499.0,35708.0,33119.0,-1270.0,...,0.4,1.1,660619.0,649969.0,145119.0,31.991436,30.365629,6.779754,30.863182,684769.0
20000,KS,Kansas,8510.0,34168.0,34547.0,34768.0,2937880.0,6984.0,32824.0,33274.0,30329.0,-1920.0,...,-0.5,-0.2,679664.0,495115.0,156595.0,31.134391,25.609931,8.099910,35.155768,601919.0
21000,KY,Kentucky,12579.0,51364.0,52384.0,52380.0,4505836.0,12785.0,58401.0,61410.0,54385.0,1010.0,...,3.1,3.7,830856.0,1006715.0,352966.0,28.836086,32.705122,11.466797,26.991996,887620.0
22000,LA,Louisiana,13555.0,57028.0,56541.0,56209.0,4657757.0,14807.0,56872.0,56876.0,50094.0,-5154.0,...,-8.5,-4.5,825794.0,1012121.0,407400.0,27.809272,32.541426,13.098609,26.550693,864939.0
23000,ME,Maine,2997.0,11590.0,12009.0,11945.0,1362359.0,3704.0,16116.0,17977.0,16998.0,1803.0,...,11.8,8.2,359323.0,310243.0,56031.0,28.627229,30.516806,5.511445,35.344521,291033.0
24000,MD,Maryland,17156.0,67431.0,68904.0,67969.0,6177224.0,16929.0,58995.0,57559.0,53770.0,-5257.0,...,-3.6,0.3,1826045.0,1014175.0,382701.0,24.571447,23.735534,8.956652,42.736366,1049892.0
25000,MA,Massachusetts,17113.0,66441.0,69069.0,68387.0,7029917.0,22133.0,61652.0,63566.0,61404.0,-27235.0,...,-2.0,1.6,2305899.0,1129802.0,425209.0,21.932898,22.844451,8.597671,46.624980,1084720.0
26000,MI,Michigan,26588.0,102799.0,104411.0,101911.0,10077331.0,31057.0,115214.0,117927.0,105941.0,-4859.0,...,1.0,0.8,2213104.0,1964538.0,564902.0,31.932879,28.195932,8.107727,31.763462,2224908.0
27000,MN,Minnesota,16461.0,63012.0,64630.0,63754.0,5706494.0,12746.0,51396.0,53436.0,49911.0,-1510.0,...,-2.6,1.7,1513374.0,916744.0,239636.0,31.502441,23.520791,6.148312,38.828456,1227836.0
28000,MS,Mississippi,8503.0,35004.0,34786.0,34628.0,2961279.0,9676.0,41703.0,40733.0,36032.0,-2122.0,...,-1.4,0.7,475997.0,589225.0,263266.0,32.574260,29.905375,13.361735,24.158630,641810.0
29000,MO,Missouri,17239.0,68820.0,68857.0,68334.0,6154913.0,16745.0,75365.0,75735.0,68389.0,-1291.0,...,2.4,3.1,1345230.0,1279442.0,354732.0,29.355020,30.336992,8.411090,31.896898,1238028.0
30000,MT,Montana,2812.0,10841.0,11219.0,11206.0,1084225.0,2518.0,12151.0,12896.0,11377.0,2746.0,...,15.8,8.9,266066.0,214759.0,41822.0,32.153284,27.878650,5.429067,34.538999,247688.0
31000,NE,Nebraska,6046.0,24410.0,24174.0,24195.0,1961504.0,4462.0,19570.0,19473.0,18496.0,-778.0,...,-0.2,2.3,440234.0,324253.0,102256.0,32.823951,25.130904,7.925249,34.119896,423513.0
32000,NV,Nevada,8167.0,33361.0,33542.0,33055.0,3104614.0,7009.0,32390.0,33435.0,29322.0,10289.0,...,9.7,4.1,601393.0,602478.0,277389.0,32.549847,27.434234,12.631091,27.384828,714821.0
33000,NH,New Hampshire,2994.0,12044.0,12332.0,12155.0,1377529.0,3481.0,13709.0,14674.0,14264.0,1272.0,...,10.0,3.7,401838.0,272558.0,59997.0,27.231769,27.006744,5.944876,39.816611,274829.0
34000,NJ,New Jersey,24722.0,98001.0,102468.0,102055.0,9288994.0,33966.0,83971.0,82566.0,76563.0,-9361.0,...,-2.9,0.5,2771686.0,1662983.0,600736.0,22.043141,25.745880,9.300442,42.910537,1423815.0
35000,NM,New Mexico,5327.0,21433.0,21151.0,20728.0,2117522.0,5523.0,24640.0,25470.0,22344.0,702.0,...,0.6,1.2,438228.0,373330.0,178146.0,31.791545,25.729170,12.277472,30.201813,461295.0
36000,NY,New York,53056.0,205414.0,210106.0,207450.0,20201249.0,72698.0,177088.0,176382.0,165914.0,-72398.0,...,-11.2,-7.3,5535503.0,3437438.0,1698537.0,23.754124,24.559904,12.135755,39.550217,3324660.0
37000,NC,North Carolina,28675.0,116747.0,121639.0,121148.0,10439388.0,25861.0,115480.0,117926.0,108491.0,12492.0,...,11.7,11.8,2521353.0,1812528.0,744581.0,30.066168,24.959728,10.253380,34.720724,2183348.0
38000,ND,North Dakota,2563.0,10019.0,9839.0,9649.0,779094.0,1751.0,7766.0,7390.0,6945.0,-448.0,...,-1.9,2.9,164378.0,130763.0,31418.0,35.861801,25.682659,6.170689,32.284852,182590.0
39000,OH,Ohio,32340.0,128271.0,128796.0,128826.0,11799448.0,33762.0,146812.0,149079.0,131288.0,-2867.0,...,1.6,2.4,2514129.0,2624935.0,680554.0,28.359331,32.313478,8.377757,30.949434,2303726.0
40000,OK,Oklahoma,11579.0,47473.0,48121.0,48073.0,3959353.0,10353.0,50805.0,51669.0,45506.0,3825.0,...,8.0,7.9,733793.0,811387.0,287078.0,30.631104,30.718938,10.868712,27.781246,809067.0
41000,OR,Oregon,10281.0,39660.0,40521.0,39046.0,4237256.0,9546.0,41943.0,46369.0,43285.0,6407.0,...,-2.4,-0.4,1094312.0,676182.0,250221.0,33.111277,22.382647,8.282694,36.223382,1000295.0
42000,PA,Pennsylvania,32903.0,130245.0,131600.0,129489.0,13002700.0,40289.0,155661.0,155062.0,140568.0,-3696.0,...,-1.1,0.1,3157318.0,3039316.0,740736.0,24.207808,33.205152,8.092693,34.494348,2215776.0
44000,RI,Rhode Island,2546.0,10030.0,10386.0,10006.0,1097379.0,3389.0,11332.0,11078.0,10434.0,-430.0,...,-2.0,2.3,289667.0,205862.0,81676.0,25.666287,26.511355,10.518413,37.303945,199300.0
45000,SC,South Carolina,13492.0,55815.0,57508.0,57581.0,5118425.0,14065.0,64911.0,64636.0,58852.0,14724.0,...,17.9,17.2,1136208.0,1019313.0,375697.0,29.890421,28.232892,10.406041,31.470645,1079156.0
46000,SD,South Dakota,2832.0,11063.0,11324.0,11369.0,886667.0,2020.0,9779.0,9226.0,8556.0,299.0,...,12.4,7.2,185411.0,175713.0,41643.0,32.437175,29.475272,6.985475,31.102079,193370.0
47000,TN,Tennessee,19250.0,79463.0,82053.0,82244.0,6910840.0,18931.0,89405.0,91616.0,81216.0,14621.0,...,13.1,10.8,1460501.0,1508292.0,499497.0,27.827153,31.386570,10.394206,30.392071,1337243.0
48000,TX,Texas,88268.0,364918.0,384024.0,390494.0,29145505.0,55732.0,270419.0,261745.0,232241.0,52914.0,...,11.5,10.4,6381971.0,4691708.0,2759723.0,28.304397,24.316132,14.303062,33.076409,5461229.0
49000,UT,Utah,11862.0,45703.0,46371.0,45965.0,3271616.0,4964.0,21993.0,23370.0,21169.0,4636.0,...,5.7,3.4,739555.0,449786.0,134602.0,33.904769,22.454675,6.719738,36.920818,679141.0
50000,VT,Vermont,1303.0,5153.0,5385.0,5072.0,643077.0,1565.0,6447.0,7216.0,6876.0,-66.0,...,3.3,3.3,197369.0,126179.0,25326.0,24.648593,27.252719,5.470026,42.628662,114122.0
51000,VA,Virginia,23580.0,94275.0,96018.0,95669.0,8631393.0,19723.0,83763.0,86329.0,79980.0,-31.0,...,1.4,2.4,2471630.0,1423702.0,516186.0,25.967764,23.891967,8.662416,41.477853,1547397.0
53000,WA,Washington,21105.0,82602.0,83874.0,82523.0,7705281.0,15173.0,64924.0,70848.0,67663.0,11889.0,...,4.2,1.7,2097154.0,1176403.0,421541.0,31.687972,21.748401,7.793114,38.770512,1714049.0
54000,WV,West Virginia,4296.0,17056.0,17100.0,17263.0,1793716.0,5871.0,27613.0,30006.0,25929.0,-813.0,...,1.2,2.7,295541.0,501118.0,144554.0,25.842143,39.482919,11.389361,23.285576,327989.0
55000,WI,Wisconsin,15554.0,60034.0,60702.0,59839.0,5893718.0,14171.0,61983.0,63601.0,58692.0,13.0,...,2.6,3.3,1333128.0,1207407.0,269431.0,30.951992,29.669059,6.620605,32.758344,1259617.0
56000,WY,Wyoming,1584.0,6164.0,6046.0,5882.0,576851.0,1290.0,6176.0,6754.0,5779.0,436.0,...,4.9,4.0,118336.0,109885.0,23502.0,36.353867,27.783537,5.942291,29.920304,143781.0
72000,PR,Puerto Rico,0.0,0.0,0.0,0.0,3285874.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,702653.0,670172.0,472462.0,23.497594,27.784172,19.587457,29.130778,566777.0

In [19]:
final_merged_data = pd.merge(data3_wide, merged_data_1_2, on=['FIPStxt', 'State', 'Area_Name'])
final_merged_data

,,Attribute,Civilian_labor_force_2019,Civilian_labor_force_2020,Civilian_labor_force_2021,Civilian_labor_force_2022,Civilian_labor_force_2023,Employed_2019,Employed_2020,Employed_2021,Employed_2022,Employed_2023,...,R_NET_MIG_2022,R_NET_MIG_2023,"Bachelor's degree or higher, 2019-23","High school graduate (or equivalency), 2019-23","Less than high school graduate, 2019-23","Percent of adults completing some college or associate degree, 2019-23","Percent of adults who are high school graduates (or equivalent), 2019-23","Percent of adults who are not high school graduates, 2019-23","Percent of adults with a bachelor's degree or higher, 2019-23","Some college or associate degree, 2019-23"
FIPStxt,State,Area_Name,,,,,,,,,,,,,,,,,,,,,
0,US,United States,163815894.0,161131754.0,161784447.0,164341251.0,166689556.0,157805901.0,148133696.0,153122706.0,158342285.0,160623678.0,...,3.0,3.4,79954302.0,59836489.0,24230217.0,28.197846,26.194137,10.607067,35.000950,64413653.0
1000,AL,Alabama,2271835.0,2263144.0,2249514.0,2276362.0,2308131.0,2199379.0,2118600.0,2173978.0,2218627.0,2250472.0,...,6.5,7.1,957081.0,1046374.0,409381.0,30.028286,30.344616,11.871959,27.755139,1035466.0
2000,AK,Alaska,352029.0,346552.0,351520.0,353692.0,357094.0,332197.0,317678.0,329147.0,338729.0,342005.0,...,-6.6,-4.8,152432.0,141206.0,31854.0,33.287559,28.941408,6.528757,31.242276,162411.0
4000,AZ,Arizona,3432400.0,3471339.0,3525449.0,3599531.0,3690974.0,3267548.0,3200219.0,3347264.0,3462671.0,3546508.0,...,12.6,7.8,1627462.0,1171693.0,544528.0,33.000824,23.477843,10.911001,32.610332,1646950.0
5000,AR,Arkansas,1353175.0,1340557.0,1330676.0,1359540.0,1377657.0,1305858.0,1257949.0,1276933.0,1315886.0,1332876.0,...,7.3,7.3,513221.0,702778.0,233857.0,29.060040,34.386203,11.442382,25.111375,593923.0
6000,CA,California,19385262.0,18958604.0,18956575.0,19169341.0,19308287.0,18589551.0,17037036.0,17568743.0,18348916.0,18388329.0,...,-5.3,-4.8,9834361.0,5496195.0,4149146.0,27.695487,20.400707,15.400748,36.503058,7461496.0
8000,CO,Colorado,3104684.0,3082228.0,3149673.0,3186932.0,3230482.0,3022060.0,2873752.0,2977479.0,3089081.0,3128115.0,...,2.9,3.3,1806355.0,811023.0,292446.0,27.948508,20.082114,7.241390,44.727988,1128710.0
9000,CT,Connecticut,1931826.0,1874247.0,1842166.0,1912008.0,1893200.0,1862314.0,1724812.0,1724540.0,1833670.0,1822088.0,...,1.5,1.7,1062403.0,647094.0,219549.0,23.839007,25.548028,8.668051,41.944913,603807.0
10000,DE,Delaware,485873.0,486701.0,493627.0,497202.0,506529.0,468539.0,450325.0,466623.0,475995.0,486404.0,...,14.9,12.3,250626.0,206192.0,61144.0,27.092993,29.023059,8.606473,35.277475,192480.0
11000,DC,District of Columbia,400641.0,386235.0,377737.0,388387.0,398251.0,378443.0,355694.0,352029.0,369952.0,378714.0,...,-0.6,8.1,307906.0,70322.0,34651.0,14.765920,14.517161,7.153297,63.563622,71527.0
11001,DC,District of Columbia,400641.0,386235.0,377737.0,388387.0,398251.0,378443.0,355694.0,352029.0,369952.0,378714.0,...,-0.6,8.1,307906.0,70322.0,34651.0,14.765920,14.517161,7.153297,63.563622,71527.0
12000,FL,Florida,10256297.0,10077028.0,10320373.0,10692183.0,10988566.0,9922941.0,9257738.0,9838506.0,10370751.0,10668886.0,...,19.9,16.6,5263931.0,4346402.0,1643437.0,28.999636,27.421577,10.368492,33.210295,4596529.0
13000,GA,Georgia,5165423.0,5082864.0,5156388.0,5222263.0,5305623.0,4980501.0,4754102.0,4954094.0,5058165.0,5135833.0,...,9.9,8.1,2480907.0,1950698.0,801324.0,27.852120,26.894828,11.048082,34.204970,2020131.0
15000,HI,Hawaii,686066.0,665964.0,670193.0,672727.0,676355.0,668769.0,588159.0,630151.0,650672.0,656336.0,...,-6.8,-4.6,364398.0,273812.0,72950.0,30.777310,26.652235,7.100786,35.469669,316191.0
16000,ID,Idaho,888611.0,899807.0,921718.0,944919.0,961506.0,862940.0,850130.0,888950.0,918106.0,931748.0,...,15.8,10.3,388032.0,322573.0,103570.0,34.568627,25.923658,8.323428,31.184286,430144.0
17000,IL,Illinois,6543691.0,6321066.0,6327675.0,6421708.0,6437855.0,6283464.0,5735263.0,5942191.0,6127480.0,6150672.0,...,-8.8,-3.4,3249494.0,2207546.0,851323.0,27.810428,25.261990,9.742090,37.185492,2430244.0
18000,IN,Indiana,3399870.0,3328778.0,3332745.0,3373887.0,3401387.0,3287462.0,3086279.0,3201829.0,3270662.0,3288017.0,...,3.0,3.3,1313086.0,1496214.0,445651.0,28.608599,32.816719,9.774540,28.800141,1304353.0
19000,IA,Iowa,1742078.0,1668401.0,1679982.0,1706493.0,1709402.0,1695474.0,1582202.0,1615303.0,1658263.0,1659106.0,...,0.4,1.1,660619.0,649969.0,145119.0,31.991436,30.365629,6.779754,30.863182,684769.0
20000,KS,Kansas,1504415.0,1501827.0,1498226.0,1502603.0,1510988.0,1456662.0,1414596.0,1448294.0,1463010.0,1470936.0,...,-0.5,-0.2,679664.0,495115.0,156595.0,31.134391,25.609931,8.099910,35.155768,601919.0
21000,KY,Kentucky,2064637.0,2005210.0,2010884.0,2030274.0,2026263.0,1979803.0,1874863.0,1921355.0,1948312.0,1941994.0,...,3.1,3.7,830856.0,1006715.0,352966.0,28.836086,32.705122,11.466797,26.991996,887620.0
22000,LA,Louisiana,2101749.0,2052043.0,2056137.0,2068817.0,2076760.0,2004115.0,1875244.0,1941271.0,1993244.0,2000152.0,...,-8.5,-4.5,825794.0,1012121.0,407400.0,27.809272,32.541426,13.098609,26.550693,864939.0
23000,ME,Maine,698261.0,671979.0,688542.0,681172.0,687322.0,678011.0,637985.0,656138.0,661833.0,667619.0,...,11.8,8.2,359323.0,310243.0,56031.0,28.627229,30.516806,5.511445,35.344521,291033.0
24000,MD,Maryland,3338480.0,3230561.0,3152885.0,3154854.0,3184868.0,3225825.0,3022470.0,2988216.0,3060216.0,3117270.0,...,-3.6,0.3,1826045.0,1014175.0,382701.0,24.571447,23.735534,8.956652,42.736366,1049892.0
25000,MA,Massachusetts,3848611.0,3744255.0,3731417.0,3743592.0,3751662.0,3731900.0,3396014.0,3530207.0,3606318.0,3625293.0,...,-2.0,1.6,2305899.0,1129802.0,425209.0,21.932898,22.844451,8.597671,46.624980,1084720.0
26000,MI,Michigan,4979516.0,4861572.0,4775153.0,4866063.0,5007904.0,4776963.0,4376032.0,4500849.0,4664171.0,4812421.0,...,1.0,0.8,2213104.0,1964538.0,564902.0,31.932879,28.195932,8.107727,31.763462,2224908.0
27000,MN,Minnesota,3111674.0,3122016.0,3049037.0,3071450.0,3099923.0,3009672.0,2926644.0,2935653.0,2992787.0,3012707.0,...,-2.6,1.7,1513374.0,916744.0,239636.0,31.502441,23.520791,6.148312,38.828456,1227836.0
28000,MS,Mississippi,1278958.0,1244316.0,1251894.0,1248093.0,1231104.0,1208541.0,1145184.0,1183867.0,1200234.0,1192015.0,...,-1.4,0.7,475997.0,589225.0,263266.0,32.574260,29.905375,13.361735,24.158630,641810.0
29000,MO,Missouri,3073523.0,3025785.0,3028635.0,3036611.0,3087759.0,2973662.0,2839617.0,2902841.0,2957352.0,2993587.0,...,2.4,3.1,1345230.0,1279442.0,354732.0,29.355020,30.336992,8.411090,31.896898,1238028.0
30000,MT,Montana,543914.0,544500.0,549105.0,564052.0,574096.0,524870.0,512744.0,530391.0,548848.0,557509.0,...,15.8,8.9,266066.0,214759.0,41822.0,32.153284,27.878650,5.429067,34.538999,247688.0
31000,NE,Nebraska,1050380.0,1045106.0,1043331.0,1050357.0,1054681.0,1017743.0,1000645.0,1015997.0,1027681.0,1030880.0,...,-0.2,2.3,440234.0,324253.0,102256.0,32.823951,25.130904,7.925249,34.119896,423513.0
32000,NV,Nevada,1545118.0,1505941.0,1500442.0,1557609.0,1602652.0,1481046.0,1302514.0,1397961.0,1476297.0,1520260.0,...,9.7,4.1,601393.0,602478.0,277389.0,32.549847,27.434234,12.631091,27.384828,714821.0
33000,NH,New Hampshire,778467.0,761429.0,753206.0,760333.0,759604.0,758463.0,710538.0,727574.0,742975.0,742886.0,...,10.0,3.7,401838.0,272558.0,59997.0,27.231769,27.006744,5.944876,39.816611,274829.0
34000,NJ,New Jersey,4687390.0,4638386.0,4648814.0,4736213.0,4829671.0,4525044.0,4200980.0,4337793.0,4552563.0,4615722.0,...,-2.9,0.5,2771686.0,1662983.0,600736.0,22.043141,25.745880,9.300442,42.910537,1423815.0
35000,NM,New Mexico,955798.0,931499.0,942420.0,947411.0,965244.0,908397.0,858100.0,875911.0,908878.0,928983.0,...,0.6,1.2,438228.0,373330.0,178146.0,31.791545,25.729170,12.277472,30.201813,461295.0
36000,NY,New York,9850900.0,9564414.0,9532961.0,9595770.0,9717791.0,9470443.0,8628006.0,8856999.0,9178585.0,9306973.0,...,-11.2,-7.3,5535503.0,3437438.0,1698537.0,23.754124,24.559904,12.135755,39.550217,3324660.0
37000,NC,North Carolina,5000820.0,4831154.0,4939281.0,5155937.0,5231638.0,4807598.0,4483551.0,4697757.0,4965568.0,5050870.0,...,11.7,11.8,2521353.0,1812528.0,744581.0,30.066168,24.959728,10.253380,34.720724,2183348.0
38000,ND,North Dakota,414120.0,409175.0,407443.0,412237.0,416722.0,405150.0,388962.0,395160.0,403886.0,408909.0,...,-1.9,2.9,164378.0,130763.0,31418.0,35.861801,25.682659,6.170689,32.284852,182590.0
39000,OH,Ohio,5879395.0,5736620.0,5708982.0,5733131.0,5786996.0,5634934.0,5266859.0,5415608.0,5503265.0,5582438.0,...,1.6,2.4,2514129.0,2624935.0,680554.0,28.359331,32.313478,8.377757,30.949434,2303726.0
40000,OK,Oklahoma,1843331.0,1842829.0,1866370.0,1903508.0,1963240.0,1785400.0,1726786.0,1791369.0,1845328.0,1899949.0,...,8.0,7.9,733793.0,811387.0,287078.0,30.631104,30.718938,10.868712,27.781246,809067.0
41000,OR,Oregon,2091454.0,2107241.0,2144461.0,2159953.0,2162127.0,2013835.0,1947540.0,2033502.0,2075083.0,2081652.0,...,-2.4,-0.4,1094312.0,676182.0,250221.0,33.111277,22.382647,8.282694,36.223382,1000295.0
42000,PA,Pennsylvania,6576454.0,6506484.0,6431855.0,6465248.0,6518343.0,6291680.0,5929949.0,6054068.0,6202046.0,6295653.0,...,-1.1,0.1,3157318.0,3039316.0,740736.0,24.207808,33.205152,8.092693,34.494348,2215776.0
44000,RI,Rhode Island,574066.0,570736.0,572546.0,571754.0,573848.0,553845.0,518282.0,540926.0,553588.0,556609.0,...,-2.0,2.3,289667.0,205862.0,81676.0,25.666287,26.511355,10.518413,37.303945,199300.0
45000,SC,South Carolina,2333533.0,2339140.0,2359169.0,2393329.0,2453060.0,2268884.0,2199751.0,2266611.0,2316435.0,2380392.0,...,17.9,17.2,1136208.0,1019313.0,375697.0,29.890421,28.232892,10.406041,31.470645,1079156.0
46000,SD,South Dakota,464665.0,464293.0,468876.0,474514.0,480238.0,451735.0,444895.0,456631.0,464946.0,470715.0,...,12.4,7.2,185411.0,175713.0,41643.0,32.437175,29.475272,6.985475,31.102079,193370.0
47000,TN,Tennessee,3339445.0,3299159.0,3321355.0,3361979.0,3379605.0,3227700.0,3053560.0,3172858.0,3247975.0,3267935.0,...,13.1,10.8,1460501.0,1508292.0,499497.0,27.827153,31.386570,10.394206,30.392071,1337243.0
48000,TX,Texas,13927670.0,13941490.0,14292315.0,14672312.0,15067153.0,13434744.0,12872070.0,13486624.0,14093906.0,14472524.0,...,11.5,10.4,6381971.0,4691708.0,2759723.0,28.304397,24.316132,14.303062,33.076409,5461229.0
49000,UT,Utah,1619079.0,1644201.0,1683325.0,1737741.0,1790381.0,1577970.0,1564747.0,1636957.0,1696513.0,1743223.0,...,5.7,3.4,739555.0,449786.0,134602.0,33.904769,22.454675,6.719738,36.920818,679141.0
50000,VT,Vermont,353432.0,339758.0,336265.0,343550.0,350886.0,346059.0,320708.0,324166.0,335547.0,343840.0,...,3.3,3.3,197369.0,126179.0,25326.0,24.648593,27.252719,5.470026,42.628662,114122.0
51000,VA,Virginia,4419378.0,4332338.0,4315045.0,4427292.0,4555208.0,4297265.0,4053387.0,4148175.0,4304759.0,4424155.0,...,1.4,2.4,2471630.0,1423702.0,516186.0,25.967764,23.891967,8.662416,41.477853,1547397.0
53000,WA,Washington,3960885.0,3891363.0,3869163.0,3969967.0,4025762.0,3794004.0,3560168.0,3667123.0,3806848.0,3860883.0,...,4.2,1.7,2097154.0,1176403.0,421541.0,31.687972,21.748401,7.793114,38.770512,1714049.0
54000,WV,West Virginia,794874.0,777139.0,773616.0,778705.0,785642.0,755523.0,713044.0,733825.0,748269.0,754986.0,...,1.2,2.7,295541.0,501118.0,144554.0,25.842143,39.482919,11.389361,23.285576,327989.0
55000,WI,Wisconsin,3117744.0,3100674.0,3106511.0,3094981.0,3133909.0,3017904.0,2900956.0,2986636.0,3004778.0,3038960.0,...,2.6,3.3,1333128.0,1207407.0,269431.0,30.951992,29.669059,6.620605,32.758344,1259617.0
56000,WY,Wyoming,293997.0,293606.0,288769.0,292664.0,295207.0,283071.0,276367.0,275633.0,282615.0,286669.0,...,4.9,4.0,118336.0,109885.0,23502.0,36.353867,27.783537,5.942291,29.920304,143781.0
72000,PR,Puerto Rico,1090852.0,0.0,1171949.0,1187414.0,1197463.0,1000363.0,0.0,1079112.0,1115938.0,1127126.0,...,0.0,0.0,702653.0,670172.0,472462.0,23.497594,27.784172,19.587457,29.130778,566777.0

### Data Output

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you want to output your merged dataset.</span>
</div>

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>Data Output:</i></b> replace the output path <b><mark>'data/sample_use_only/sample_output/sample_merged_data.csv'</mark></b> with your path <b><mark>'data/{your_merged_data.csv}'</mark></b>.</span>
</div>

In [20]:
final_merged_data.to_csv('data/sample_use_only/sample_output/sample_merged_data.csv')